// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"remi/server/ent/calendarmeeting"
	"remi/server/ent/predicate"
	"remi/server/ent/user"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// CalendarMeetingUpdate is the builder for updating CalendarMeeting entities.
type CalendarMeetingUpdate struct {
	config
	hooks    []Hook
	mutation *CalendarMeetingMutation
}

// Where appends a list predicates to the CalendarMeetingUpdate builder.
func (_u *CalendarMeetingUpdate) Where(ps ...predicate.CalendarMeeting) *CalendarMeetingUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CalendarMeetingUpdate) SetUpdatedAt(v time.Time) *CalendarMeetingUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetExternalID sets the "external_id" field.
func (_u *CalendarMeetingUpdate) SetExternalID(v string) *CalendarMeetingUpdate {
	_u.mutation.SetExternalID(v)
	return _u
}

// SetNillableExternalID sets the "external_id" field if the given value is not nil.
func (_u *CalendarMeetingUpdate) SetNillableExternalID(v *string) *CalendarMeetingUpdate {
	if v != nil {
		_u.SetExternalID(*v)
	}
	return _u
}

// SetCalendarEventID sets the "calendar_event_id" field.
func (_u *CalendarMeetingUpdate) SetCalendarEventID(v string) *CalendarMeetingUpdate {
	_u.mutation.SetCalendarEventID(v)
	return _u
}

// SetNillableCalendarEventID sets the "calendar_event_id" field if the given value is not nil.
func (_u *CalendarMeetingUpdate) SetNillableCalendarEventID(v *string) *CalendarMeetingUpdate {
	if v != nil {
		_u.SetCalendarEventID(*v)
	}
	return _u
}

// SetCalendarSource sets the "calendar_source" field.
func (_u *CalendarMeetingUpdate) SetCalendarSource(v string) *CalendarMeetingUpdate {
	_u.mutation.SetCalendarSource(v)
	return _u
}

// SetNillableCalendarSource sets the "calendar_source" field if the given value is not nil.
func (_u *CalendarMeetingUpdate) SetNillableCalendarSource(v *string) *CalendarMeetingUpdate {
	if v != nil {
		_u.SetCalendarSource(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *CalendarMeetingUpdate) SetTitle(v string) *CalendarMeetingUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *CalendarMeetingUpdate) SetNillableTitle(v *string) *CalendarMeetingUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetParticipants sets the "participants" field.
func (_u *CalendarMeetingUpdate) SetParticipants(v []map[string]interface{}) *CalendarMeetingUpdate {
	_u.mutation.SetParticipants(v)
	return _u
}

// AppendParticipants appends value to the "participants" field.
func (_u *CalendarMeetingUpdate) AppendParticipants(v []map[string]interface{}) *CalendarMeetingUpdate {
	_u.mutation.AppendParticipants(v)
	return _u
}

// ClearParticipants clears the value of the "participants" field.
func (_u *CalendarMeetingUpdate) ClearParticipants() *CalendarMeetingUpdate {
	_u.mutation.ClearParticipants()
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *CalendarMeetingUpdate) SetPlatform(v string) *CalendarMeetingUpdate {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *CalendarMeetingUpdate) SetNillablePlatform(v *string) *CalendarMeetingUpdate {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// ClearPlatform clears the value of the "platform" field.
func (_u *CalendarMeetingUpdate) ClearPlatform() *CalendarMeetingUpdate {
	_u.mutation.ClearPlatform()
	return _u
}

// SetMeetingLink sets the "meeting_link" field.
func (_u *CalendarMeetingUpdate) SetMeetingLink(v string) *CalendarMeetingUpdate {
	_u.mutation.SetMeetingLink(v)
	return _u
}

// SetNillableMeetingLink sets the "meeting_link" field if the given value is not nil.
func (_u *CalendarMeetingUpdate) SetNillableMeetingLink(v *string) *CalendarMeetingUpdate {
	if v != nil {
		_u.SetMeetingLink(*v)
	}
	return _u
}

// ClearMeetingLink clears the value of the "meeting_link" field.
func (_u *CalendarMeetingUpdate) ClearMeetingLink() *CalendarMeetingUpdate {
	_u.mutation.ClearMeetingLink()
	return _u
}

// SetStartTime sets the "start_time" field.
func (_u *CalendarMeetingUpdate) SetStartTime(v time.Time) *CalendarMeetingUpdate {
	_u.mutation.SetStartTime(v)
	return _u
}

// SetNillableStartTime sets the "start_time" field if the given value is not nil.
func (_u *CalendarMeetingUpdate) SetNillableStartTime(v *time.Time) *CalendarMeetingUpdate {
	if v != nil {
		_u.SetStartTime(*v)
	}
	return _u
}

// SetEndTime sets the "end_time" field.
func (_u *CalendarMeetingUpdate) SetEndTime(v time.Time) *CalendarMeetingUpdate {
	_u.mutation.SetEndTime(v)
	return _u
}

// SetNillableEndTime sets the "end_time" field if the given value is not nil.
func (_u *CalendarMeetingUpdate) SetNillableEndTime(v *time.Time) *CalendarMeetingUpdate {
	if v != nil {
		_u.SetEndTime(*v)
	}
	return _u
}

// SetDurationMinutes sets the "duration_minutes" field.
func (_u *CalendarMeetingUpdate) SetDurationMinutes(v int) *CalendarMeetingUpdate {
	_u.mutation.ResetDurationMinutes()
	_u.mutation.SetDurationMinutes(v)
	return _u
}

// SetNillableDurationMinutes sets the "duration_minutes" field if the given value is not nil.
func (_u *CalendarMeetingUpdate) SetNillableDurationMinutes(v *int) *CalendarMeetingUpdate {
	if v != nil {
		_u.SetDurationMinutes(*v)
	}
	return _u
}

// AddDurationMinutes adds value to the "duration_minutes" field.
func (_u *CalendarMeetingUpdate) AddDurationMinutes(v int) *CalendarMeetingUpdate {
	_u.mutation.AddDurationMinutes(v)
	return _u
}

// SetNotes sets the "notes" field.
func (_u *CalendarMeetingUpdate) SetNotes(v string) *CalendarMeetingUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *CalendarMeetingUpdate) SetNillableNotes(v *string) *CalendarMeetingUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *CalendarMeetingUpdate) ClearNotes() *CalendarMeetingUpdate {
	_u.mutation.ClearNotes()
	return _u
}

// SetSyncedAt sets the "synced_at" field.
func (_u *CalendarMeetingUpdate) SetSyncedAt(v time.Time) *CalendarMeetingUpdate {
	_u.mutation.SetSyncedAt(v)
	return _u
}

// SetNillableSyncedAt sets the "synced_at" field if the given value is not nil.
func (_u *CalendarMeetingUpdate) SetNillableSyncedAt(v *time.Time) *CalendarMeetingUpdate {
	if v != nil {
		_u.SetSyncedAt(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *CalendarMeetingUpdate) SetUserID(v int) *CalendarMeetingUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *CalendarMeetingUpdate) SetNillableUserID(v *int) *CalendarMeetingUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *CalendarMeetingUpdate) ClearUserID() *CalendarMeetingUpdate {
	_u.mutation.ClearUserID()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *CalendarMeetingUpdate) SetUser(v *User) *CalendarMeetingUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the CalendarMeetingMutation object of the builder.
func (_u *CalendarMeetingUpdate) Mutation() *CalendarMeetingMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *CalendarMeetingUpdate) ClearUser() *CalendarMeetingUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CalendarMeetingUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CalendarMeetingUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CalendarMeetingUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CalendarMeetingUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CalendarMeetingUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := calendarmeeting.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CalendarMeetingUpdate) check() error {
	if v, ok := _u.mutation.CalendarEventID(); ok {
		if err := calendarmeeting.CalendarEventIDValidator(v); err != nil {
			return &ValidationError{Name: "calendar_event_id", err: fmt.Errorf(`ent: validator failed for field "CalendarMeeting.calendar_event_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := calendarmeeting.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "CalendarMeeting.title": %w`, err)}
		}
	}
	return nil
}

func (_u *CalendarMeetingUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(calendarmeeting.Table, calendarmeeting.Columns, sqlgraph.NewFieldSpec(calendarmeeting.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(calendarmeeting.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExternalID(); ok {
		_spec.SetField(calendarmeeting.FieldExternalID, field.TypeString, value)
	}
	if value, ok := _u.mutation.CalendarEventID(); ok {
		_spec.SetField(calendarmeeting.FieldCalendarEventID, field.TypeString, value)
	}
	if value, ok := _u.mutation.CalendarSource(); ok {
		_spec.SetField(calendarmeeting.FieldCalendarSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(calendarmeeting.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Participants(); ok {
		_spec.SetField(calendarmeeting.FieldParticipants, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedParticipants(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, calendarmeeting.FieldParticipants, value)
		})
	}
	if _u.mutation.ParticipantsCleared() {
		_spec.ClearField(calendarmeeting.FieldParticipants, field.TypeJSON)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(calendarmeeting.FieldPlatform, field.TypeString, value)
	}
	if _u.mutation.PlatformCleared() {
		_spec.ClearField(calendarmeeting.FieldPlatform, field.TypeString)
	}
	if value, ok := _u.mutation.MeetingLink(); ok {
		_spec.SetField(calendarmeeting.FieldMeetingLink, field.TypeString, value)
	}
	if _u.mutation.MeetingLinkCleared() {
		_spec.ClearField(calendarmeeting.FieldMeetingLink, field.TypeString)
	}
	if value, ok := _u.mutation.StartTime(); ok {
		_spec.SetField(calendarmeeting.FieldStartTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EndTime(); ok {
		_spec.SetField(calendarmeeting.FieldEndTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DurationMinutes(); ok {
		_spec.SetField(calendarmeeting.FieldDurationMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDurationMinutes(); ok {
		_spec.AddField(calendarmeeting.FieldDurationMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(calendarmeeting.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(calendarmeeting.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.SyncedAt(); ok {
		_spec.SetField(calendarmeeting.FieldSyncedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   calendarmeeting.UserTable,
			Columns: []string{calendarmeeting.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   calendarmeeting.UserTable,
			Columns: []string{calendarmeeting.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{calendarmeeting.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CalendarMeetingUpdateOne is the builder for updating a single CalendarMeeting entity.
type CalendarMeetingUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CalendarMeetingMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CalendarMeetingUpdateOne) SetUpdatedAt(v time.Time) *CalendarMeetingUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetExternalID sets the "external_id" field.
func (_u *CalendarMeetingUpdateOne) SetExternalID(v string) *CalendarMeetingUpdateOne {
	_u.mutation.SetExternalID(v)
	return _u
}

// SetNillableExternalID sets the "external_id" field if the given value is not nil.
func (_u *CalendarMeetingUpdateOne) SetNillableExternalID(v *string) *CalendarMeetingUpdateOne {
	if v != nil {
		_u.SetExternalID(*v)
	}
	return _u
}

// SetCalendarEventID sets the "calendar_event_id" field.
func (_u *CalendarMeetingUpdateOne) SetCalendarEventID(v string) *CalendarMeetingUpdateOne {
	_u.mutation.SetCalendarEventID(v)
	return _u
}

// SetNillableCalendarEventID sets the "calendar_event_id" field if the given value is not nil.
func (_u *CalendarMeetingUpdateOne) SetNillableCalendarEventID(v *string) *CalendarMeetingUpdateOne {
	if v != nil {
		_u.SetCalendarEventID(*v)
	}
	return _u
}

// SetCalendarSource sets the "calendar_source" field.
func (_u *CalendarMeetingUpdateOne) SetCalendarSource(v string) *CalendarMeetingUpdateOne {
	_u.mutation.SetCalendarSource(v)
	return _u
}

// SetNillableCalendarSource sets the "calendar_source" field if the given value is not nil.
func (_u *CalendarMeetingUpdateOne) SetNillableCalendarSource(v *string) *CalendarMeetingUpdateOne {
	if v != nil {
		_u.SetCalendarSource(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *CalendarMeetingUpdateOne) SetTitle(v string) *CalendarMeetingUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *CalendarMeetingUpdateOne) SetNillableTitle(v *string) *CalendarMeetingUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetParticipants sets the "participants" field.
func (_u *CalendarMeetingUpdateOne) SetParticipants(v []map[string]interface{}) *CalendarMeetingUpdateOne {
	_u.mutation.SetParticipants(v)
	return _u
}

// AppendParticipants appends value to the "participants" field.
func (_u *CalendarMeetingUpdateOne) AppendParticipants(v []map[string]interface{}) *CalendarMeetingUpdateOne {
	_u.mutation.AppendParticipants(v)
	return _u
}

// ClearParticipants clears the value of the "participants" field.
func (_u *CalendarMeetingUpdateOne) ClearParticipants() *CalendarMeetingUpdateOne {
	_u.mutation.ClearParticipants()
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *CalendarMeetingUpdateOne) SetPlatform(v string) *CalendarMeetingUpdateOne {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *CalendarMeetingUpdateOne) SetNillablePlatform(v *string) *CalendarMeetingUpdateOne {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// ClearPlatform clears the value of the "platform" field.
func (_u *CalendarMeetingUpdateOne) ClearPlatform() *CalendarMeetingUpdateOne {
	_u.mutation.ClearPlatform()
	return _u
}

// SetMeetingLink sets the "meeting_link" field.
func (_u *CalendarMeetingUpdateOne) SetMeetingLink(v string) *CalendarMeetingUpdateOne {
	_u.mutation.SetMeetingLink(v)
	return _u
}

// SetNillableMeetingLink sets the "meeting_link" field if the given value is not nil.
func (_u *CalendarMeetingUpdateOne) SetNillableMeetingLink(v *string) *CalendarMeetingUpdateOne {
	if v != nil {
		_u.SetMeetingLink(*v)
	}
	return _u
}

// ClearMeetingLink clears the value of the "meeting_link" field.
func (_u *CalendarMeetingUpdateOne) ClearMeetingLink() *CalendarMeetingUpdateOne {
	_u.mutation.ClearMeetingLink()
	return _u
}

// SetStartTime sets the "start_time" field.
func (_u *CalendarMeetingUpdateOne) SetStartTime(v time.Time) *CalendarMeetingUpdateOne {
	_u.mutation.SetStartTime(v)
	return _u
}

// SetNillableStartTime sets the "start_time" field if the given value is not nil.
func (_u *CalendarMeetingUpdateOne) SetNillableStartTime(v *time.Time) *CalendarMeetingUpdateOne {
	if v != nil {
		_u.SetStartTime(*v)
	}
	return _u
}

// SetEndTime sets the "end_time" field.
func (_u *CalendarMeetingUpdateOne) SetEndTime(v time.Time) *CalendarMeetingUpdateOne {
	_u.mutation.SetEndTime(v)
	return _u
}

// SetNillableEndTime sets the "end_time" field if the given value is not nil.
func (_u *CalendarMeetingUpdateOne) SetNillableEndTime(v *time.Time) *CalendarMeetingUpdateOne {
	if v != nil {
		_u.SetEndTime(*v)
	}
	return _u
}

// SetDurationMinutes sets the "duration_minutes" field.
func (_u *CalendarMeetingUpdateOne) SetDurationMinutes(v int) *CalendarMeetingUpdateOne {
	_u.mutation.ResetDurationMinutes()
	_u.mutation.SetDurationMinutes(v)
	return _u
}

// SetNillableDurationMinutes sets the "duration_minutes" field if the given value is not nil.
func (_u *CalendarMeetingUpdateOne) SetNillableDurationMinutes(v *int) *CalendarMeetingUpdateOne {
	if v != nil {
		_u.SetDurationMinutes(*v)
	}
	return _u
}

// AddDurationMinutes adds value to the "duration_minutes" field.
func (_u *CalendarMeetingUpdateOne) AddDurationMinutes(v int) *CalendarMeetingUpdateOne {
	_u.mutation.AddDurationMinutes(v)
	return _u
}

// SetNotes sets the "notes" field.
func (_u *CalendarMeetingUpdateOne) SetNotes(v string) *CalendarMeetingUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *CalendarMeetingUpdateOne) SetNillableNotes(v *string) *CalendarMeetingUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *CalendarMeetingUpdateOne) ClearNotes() *CalendarMeetingUpdateOne {
	_u.mutation.ClearNotes()
	return _u
}

// SetSyncedAt sets the "synced_at" field.
func (_u *CalendarMeetingUpdateOne) SetSyncedAt(v time.Time) *CalendarMeetingUpdateOne {
	_u.mutation.SetSyncedAt(v)
	return _u
}

// SetNillableSyncedAt sets the "synced_at" field if the given value is not nil.
func (_u *CalendarMeetingUpdateOne) SetNillableSyncedAt(v *time.Time) *CalendarMeetingUpdateOne {
	if v != nil {
		_u.SetSyncedAt(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *CalendarMeetingUpdateOne) SetUserID(v int) *CalendarMeetingUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *CalendarMeetingUpdateOne) SetNillableUserID(v *int) *CalendarMeetingUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *CalendarMeetingUpdateOne) ClearUserID() *CalendarMeetingUpdateOne {
	_u.mutation.ClearUserID()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *CalendarMeetingUpdateOne) SetUser(v *User) *CalendarMeetingUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the CalendarMeetingMutation object of the builder.
func (_u *CalendarMeetingUpdateOne) Mutation() *CalendarMeetingMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *CalendarMeetingUpdateOne) ClearUser() *CalendarMeetingUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the CalendarMeetingUpdate builder.
func (_u *CalendarMeetingUpdateOne) Where(ps ...predicate.CalendarMeeting) *CalendarMeetingUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CalendarMeetingUpdateOne) Select(field string, fields ...string) *CalendarMeetingUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CalendarMeeting entity.
func (_u *CalendarMeetingUpdateOne) Save(ctx context.Context) (*CalendarMeeting, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CalendarMeetingUpdateOne) SaveX(ctx context.Context) *CalendarMeeting {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CalendarMeetingUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CalendarMeetingUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CalendarMeetingUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := calendarmeeting.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CalendarMeetingUpdateOne) check() error {
	if v, ok := _u.mutation.CalendarEventID(); ok {
		if err := calendarmeeting.CalendarEventIDValidator(v); err != nil {
			return &ValidationError{Name: "calendar_event_id", err: fmt.Errorf(`ent: validator failed for field "CalendarMeeting.calendar_event_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := calendarmeeting.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "CalendarMeeting.title": %w`, err)}
		}
	}
	return nil
}

func (_u *CalendarMeetingUpdateOne) sqlSave(ctx context.Context) (_node *CalendarMeeting, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(calendarmeeting.Table, calendarmeeting.Columns, sqlgraph.NewFieldSpec(calendarmeeting.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CalendarMeeting.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, calendarmeeting.FieldID)
		for _, f := range fields {
			if !calendarmeeting.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != calendarmeeting.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(calendarmeeting.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExternalID(); ok {
		_spec.SetField(calendarmeeting.FieldExternalID, field.TypeString, value)
	}
	if value, ok := _u.mutation.CalendarEventID(); ok {
		_spec.SetField(calendarmeeting.FieldCalendarEventID, field.TypeString, value)
	}
	if value, ok := _u.mutation.CalendarSource(); ok {
		_spec.SetField(calendarmeeting.FieldCalendarSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(calendarmeeting.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Participants(); ok {
		_spec.SetField(calendarmeeting.FieldParticipants, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedParticipants(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, calendarmeeting.FieldParticipants, value)
		})
	}
	if _u.mutation.ParticipantsCleared() {
		_spec.ClearField(calendarmeeting.FieldParticipants, field.TypeJSON)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(calendarmeeting.FieldPlatform, field.TypeString, value)
	}
	if _u.mutation.PlatformCleared() {
		_spec.ClearField(calendarmeeting.FieldPlatform, field.TypeString)
	}
	if value, ok := _u.mutation.MeetingLink(); ok {
		_spec.SetField(calendarmeeting.FieldMeetingLink, field.TypeString, value)
	}
	if _u.mutation.MeetingLinkCleared() {
		_spec.ClearField(calendarmeeting.FieldMeetingLink, field.TypeString)
	}
	if value, ok := _u.mutation.StartTime(); ok {
		_spec.SetField(calendarmeeting.FieldStartTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EndTime(); ok {
		_spec.SetField(calendarmeeting.FieldEndTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DurationMinutes(); ok {
		_spec.SetField(calendarmeeting.FieldDurationMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDurationMinutes(); ok {
		_spec.AddField(calendarmeeting.FieldDurationMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(calendarmeeting.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(calendarmeeting.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.SyncedAt(); ok {
		_spec.SetField(calendarmeeting.FieldSyncedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   calendarmeeting.UserTable,
			Columns: []string{calendarmeeting.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   calendarmeeting.UserTable,
			Columns: []string{calendarmeeting.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &CalendarMeeting{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{calendarmeeting.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
