// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"remi/server/ent/chatfile"
	"remi/server/ent/user"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ChatFileCreate is the builder for creating a ChatFile entity.
type ChatFileCreate struct {
	config
	mutation *ChatFileMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *ChatFileCreate) SetCreatedAt(v time.Time) *ChatFileCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ChatFileCreate) SetNillableCreatedAt(v *time.Time) *ChatFileCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ChatFileCreate) SetUpdatedAt(v time.Time) *ChatFileCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ChatFileCreate) SetNillableUpdatedAt(v *time.Time) *ChatFileCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetExternalID sets the "external_id" field.
func (_c *ChatFileCreate) SetExternalID(v string) *ChatFileCreate {
	_c.mutation.SetExternalID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *ChatFileCreate) SetName(v string) *ChatFileCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetThumbnail sets the "thumbnail" field.
func (_c *ChatFileCreate) SetThumbnail(v string) *ChatFileCreate {
	_c.mutation.SetThumbnail(v)
	return _c
}

// SetNillableThumbnail sets the "thumbnail" field if the given value is not nil.
func (_c *ChatFileCreate) SetNillableThumbnail(v *string) *ChatFileCreate {
	if v != nil {
		_c.SetThumbnail(*v)
	}
	return _c
}

// SetMimeType sets the "mime_type" field.
func (_c *ChatFileCreate) SetMimeType(v string) *ChatFileCreate {
	_c.mutation.SetMimeType(v)
	return _c
}

// SetOpenaiFileID sets the "openai_file_id" field.
func (_c *ChatFileCreate) SetOpenaiFileID(v string) *ChatFileCreate {
	_c.mutation.SetOpenaiFileID(v)
	return _c
}

// SetThumbName sets the "thumb_name" field.
func (_c *ChatFileCreate) SetThumbName(v string) *ChatFileCreate {
	_c.mutation.SetThumbName(v)
	return _c
}

// SetNillableThumbName sets the "thumb_name" field if the given value is not nil.
func (_c *ChatFileCreate) SetNillableThumbName(v *string) *ChatFileCreate {
	if v != nil {
		_c.SetThumbName(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *ChatFileCreate) SetUserID(v int) *ChatFileCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_c *ChatFileCreate) SetNillableUserID(v *int) *ChatFileCreate {
	if v != nil {
		_c.SetUserID(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *ChatFileCreate) SetUser(v *User) *ChatFileCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the ChatFileMutation object of the builder.
func (_c *ChatFileCreate) Mutation() *ChatFileMutation {
	return _c.mutation
}

// Save creates the ChatFile in the database.
func (_c *ChatFileCreate) Save(ctx context.Context) (*ChatFile, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ChatFileCreate) SaveX(ctx context.Context) *ChatFile {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChatFileCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChatFileCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ChatFileCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := chatfile.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := chatfile.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Thumbnail(); !ok {
		v := chatfile.DefaultThumbnail
		_c.mutation.SetThumbnail(v)
	}
	if _, ok := _c.mutation.ThumbName(); !ok {
		v := chatfile.DefaultThumbName
		_c.mutation.SetThumbName(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ChatFileCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ChatFile.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ChatFile.updated_at"`)}
	}
	if _, ok := _c.mutation.ExternalID(); !ok {
		return &ValidationError{Name: "external_id", err: errors.New(`ent: missing required field "ChatFile.external_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "ChatFile.name"`)}
	}
	if _, ok := _c.mutation.Thumbnail(); !ok {
		return &ValidationError{Name: "thumbnail", err: errors.New(`ent: missing required field "ChatFile.thumbnail"`)}
	}
	if _, ok := _c.mutation.MimeType(); !ok {
		return &ValidationError{Name: "mime_type", err: errors.New(`ent: missing required field "ChatFile.mime_type"`)}
	}
	if _, ok := _c.mutation.OpenaiFileID(); !ok {
		return &ValidationError{Name: "openai_file_id", err: errors.New(`ent: missing required field "ChatFile.openai_file_id"`)}
	}
	if _, ok := _c.mutation.ThumbName(); !ok {
		return &ValidationError{Name: "thumb_name", err: errors.New(`ent: missing required field "ChatFile.thumb_name"`)}
	}
	return nil
}

func (_c *ChatFileCreate) sqlSave(ctx context.Context) (*ChatFile, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ChatFileCreate) createSpec() (*ChatFile, *sqlgraph.CreateSpec) {
	var (
		_node = &ChatFile{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(chatfile.Table, sqlgraph.NewFieldSpec(chatfile.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(chatfile.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(chatfile.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.ExternalID(); ok {
		_spec.SetField(chatfile.FieldExternalID, field.TypeString, value)
		_node.ExternalID = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(chatfile.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Thumbnail(); ok {
		_spec.SetField(chatfile.FieldThumbnail, field.TypeString, value)
		_node.Thumbnail = value
	}
	if value, ok := _c.mutation.MimeType(); ok {
		_spec.SetField(chatfile.FieldMimeType, field.TypeString, value)
		_node.MimeType = value
	}
	if value, ok := _c.mutation.OpenaiFileID(); ok {
		_spec.SetField(chatfile.FieldOpenaiFileID, field.TypeString, value)
		_node.OpenaiFileID = value
	}
	if value, ok := _c.mutation.ThumbName(); ok {
		_spec.SetField(chatfile.FieldThumbName, field.TypeString, value)
		_node.ThumbName = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatfile.UserTable,
			Columns: []string{chatfile.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ChatFileCreateBulk is the builder for creating many ChatFile entities in bulk.
type ChatFileCreateBulk struct {
	config
	err      error
	builders []*ChatFileCreate
}

// Save creates the ChatFile entities in the database.
func (_c *ChatFileCreateBulk) Save(ctx context.Context) ([]*ChatFile, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ChatFile, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ChatFileMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ChatFileCreateBulk) SaveX(ctx context.Context) []*ChatFile {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChatFileCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChatFileCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
