// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"remi/server/ent/chatmessage"
	"remi/server/ent/user"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ChatMessageCreate is the builder for creating a ChatMessage entity.
type ChatMessageCreate struct {
	config
	mutation *ChatMessageMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *ChatMessageCreate) SetCreatedAt(v time.Time) *ChatMessageCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ChatMessageCreate) SetNillableCreatedAt(v *time.Time) *ChatMessageCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ChatMessageCreate) SetUpdatedAt(v time.Time) *ChatMessageCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ChatMessageCreate) SetNillableUpdatedAt(v *time.Time) *ChatMessageCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetExternalID sets the "external_id" field.
func (_c *ChatMessageCreate) SetExternalID(v string) *ChatMessageCreate {
	_c.mutation.SetExternalID(v)
	return _c
}

// SetText sets the "text" field.
func (_c *ChatMessageCreate) SetText(v string) *ChatMessageCreate {
	_c.mutation.SetText(v)
	return _c
}

// SetSender sets the "sender" field.
func (_c *ChatMessageCreate) SetSender(v chatmessage.Sender) *ChatMessageCreate {
	_c.mutation.SetSender(v)
	return _c
}

// SetType sets the "type" field.
func (_c *ChatMessageCreate) SetType(v chatmessage.Type) *ChatMessageCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_c *ChatMessageCreate) SetNillableType(v *chatmessage.Type) *ChatMessageCreate {
	if v != nil {
		_c.SetType(*v)
	}
	return _c
}

// SetAppID sets the "app_id" field.
func (_c *ChatMessageCreate) SetAppID(v string) *ChatMessageCreate {
	_c.mutation.SetAppID(v)
	return _c
}

// SetNillableAppID sets the "app_id" field if the given value is not nil.
func (_c *ChatMessageCreate) SetNillableAppID(v *string) *ChatMessageCreate {
	if v != nil {
		_c.SetAppID(*v)
	}
	return _c
}

// SetChatSessionID sets the "chat_session_id" field.
func (_c *ChatMessageCreate) SetChatSessionID(v string) *ChatMessageCreate {
	_c.mutation.SetChatSessionID(v)
	return _c
}

// SetNillableChatSessionID sets the "chat_session_id" field if the given value is not nil.
func (_c *ChatMessageCreate) SetNillableChatSessionID(v *string) *ChatMessageCreate {
	if v != nil {
		_c.SetChatSessionID(*v)
	}
	return _c
}

// SetRating sets the "rating" field.
func (_c *ChatMessageCreate) SetRating(v int) *ChatMessageCreate {
	_c.mutation.SetRating(v)
	return _c
}

// SetNillableRating sets the "rating" field if the given value is not nil.
func (_c *ChatMessageCreate) SetNillableRating(v *int) *ChatMessageCreate {
	if v != nil {
		_c.SetRating(*v)
	}
	return _c
}

// SetReported sets the "reported" field.
func (_c *ChatMessageCreate) SetReported(v bool) *ChatMessageCreate {
	_c.mutation.SetReported(v)
	return _c
}

// SetNillableReported sets the "reported" field if the given value is not nil.
func (_c *ChatMessageCreate) SetNillableReported(v *bool) *ChatMessageCreate {
	if v != nil {
		_c.SetReported(*v)
	}
	return _c
}

// SetReportReason sets the "report_reason" field.
func (_c *ChatMessageCreate) SetReportReason(v string) *ChatMessageCreate {
	_c.mutation.SetReportReason(v)
	return _c
}

// SetNillableReportReason sets the "report_reason" field if the given value is not nil.
func (_c *ChatMessageCreate) SetNillableReportReason(v *string) *ChatMessageCreate {
	if v != nil {
		_c.SetReportReason(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *ChatMessageCreate) SetUserID(v int) *ChatMessageCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_c *ChatMessageCreate) SetNillableUserID(v *int) *ChatMessageCreate {
	if v != nil {
		_c.SetUserID(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *ChatMessageCreate) SetUser(v *User) *ChatMessageCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the ChatMessageMutation object of the builder.
func (_c *ChatMessageCreate) Mutation() *ChatMessageMutation {
	return _c.mutation
}

// Save creates the ChatMessage in the database.
func (_c *ChatMessageCreate) Save(ctx context.Context) (*ChatMessage, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ChatMessageCreate) SaveX(ctx context.Context) *ChatMessage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChatMessageCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChatMessageCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ChatMessageCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := chatmessage.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := chatmessage.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.GetType(); !ok {
		v := chatmessage.DefaultType
		_c.mutation.SetType(v)
	}
	if _, ok := _c.mutation.Reported(); !ok {
		v := chatmessage.DefaultReported
		_c.mutation.SetReported(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ChatMessageCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ChatMessage.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ChatMessage.updated_at"`)}
	}
	if _, ok := _c.mutation.ExternalID(); !ok {
		return &ValidationError{Name: "external_id", err: errors.New(`ent: missing required field "ChatMessage.external_id"`)}
	}
	if _, ok := _c.mutation.Text(); !ok {
		return &ValidationError{Name: "text", err: errors.New(`ent: missing required field "ChatMessage.text"`)}
	}
	if _, ok := _c.mutation.Sender(); !ok {
		return &ValidationError{Name: "sender", err: errors.New(`ent: missing required field "ChatMessage.sender"`)}
	}
	if v, ok := _c.mutation.Sender(); ok {
		if err := chatmessage.SenderValidator(v); err != nil {
			return &ValidationError{Name: "sender", err: fmt.Errorf(`ent: validator failed for field "ChatMessage.sender": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "ChatMessage.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := chatmessage.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "ChatMessage.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Reported(); !ok {
		return &ValidationError{Name: "reported", err: errors.New(`ent: missing required field "ChatMessage.reported"`)}
	}
	return nil
}

func (_c *ChatMessageCreate) sqlSave(ctx context.Context) (*ChatMessage, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ChatMessageCreate) createSpec() (*ChatMessage, *sqlgraph.CreateSpec) {
	var (
		_node = &ChatMessage{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(chatmessage.Table, sqlgraph.NewFieldSpec(chatmessage.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(chatmessage.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(chatmessage.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.ExternalID(); ok {
		_spec.SetField(chatmessage.FieldExternalID, field.TypeString, value)
		_node.ExternalID = value
	}
	if value, ok := _c.mutation.Text(); ok {
		_spec.SetField(chatmessage.FieldText, field.TypeString, value)
		_node.Text = value
	}
	if value, ok := _c.mutation.Sender(); ok {
		_spec.SetField(chatmessage.FieldSender, field.TypeEnum, value)
		_node.Sender = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(chatmessage.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.AppID(); ok {
		_spec.SetField(chatmessage.FieldAppID, field.TypeString, value)
		_node.AppID = &value
	}
	if value, ok := _c.mutation.ChatSessionID(); ok {
		_spec.SetField(chatmessage.FieldChatSessionID, field.TypeString, value)
		_node.ChatSessionID = &value
	}
	if value, ok := _c.mutation.Rating(); ok {
		_spec.SetField(chatmessage.FieldRating, field.TypeInt, value)
		_node.Rating = &value
	}
	if value, ok := _c.mutation.Reported(); ok {
		_spec.SetField(chatmessage.FieldReported, field.TypeBool, value)
		_node.Reported = value
	}
	if value, ok := _c.mutation.ReportReason(); ok {
		_spec.SetField(chatmessage.FieldReportReason, field.TypeString, value)
		_node.ReportReason = &value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatmessage.UserTable,
			Columns: []string{chatmessage.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ChatMessageCreateBulk is the builder for creating many ChatMessage entities in bulk.
type ChatMessageCreateBulk struct {
	config
	err      error
	builders []*ChatMessageCreate
}

// Save creates the ChatMessage entities in the database.
func (_c *ChatMessageCreateBulk) Save(ctx context.Context) ([]*ChatMessage, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ChatMessage, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ChatMessageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ChatMessageCreateBulk) SaveX(ctx context.Context) []*ChatMessage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChatMessageCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChatMessageCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
