// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"remi/server/ent/chatmessage"
	"remi/server/ent/predicate"
	"remi/server/ent/user"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ChatMessageUpdate is the builder for updating ChatMessage entities.
type ChatMessageUpdate struct {
	config
	hooks    []Hook
	mutation *ChatMessageMutation
}

// Where appends a list predicates to the ChatMessageUpdate builder.
func (_u *ChatMessageUpdate) Where(ps ...predicate.ChatMessage) *ChatMessageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ChatMessageUpdate) SetUpdatedAt(v time.Time) *ChatMessageUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetExternalID sets the "external_id" field.
func (_u *ChatMessageUpdate) SetExternalID(v string) *ChatMessageUpdate {
	_u.mutation.SetExternalID(v)
	return _u
}

// SetNillableExternalID sets the "external_id" field if the given value is not nil.
func (_u *ChatMessageUpdate) SetNillableExternalID(v *string) *ChatMessageUpdate {
	if v != nil {
		_u.SetExternalID(*v)
	}
	return _u
}

// SetText sets the "text" field.
func (_u *ChatMessageUpdate) SetText(v string) *ChatMessageUpdate {
	_u.mutation.SetText(v)
	return _u
}

// SetNillableText sets the "text" field if the given value is not nil.
func (_u *ChatMessageUpdate) SetNillableText(v *string) *ChatMessageUpdate {
	if v != nil {
		_u.SetText(*v)
	}
	return _u
}

// SetSender sets the "sender" field.
func (_u *ChatMessageUpdate) SetSender(v chatmessage.Sender) *ChatMessageUpdate {
	_u.mutation.SetSender(v)
	return _u
}

// SetNillableSender sets the "sender" field if the given value is not nil.
func (_u *ChatMessageUpdate) SetNillableSender(v *chatmessage.Sender) *ChatMessageUpdate {
	if v != nil {
		_u.SetSender(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *ChatMessageUpdate) SetType(v chatmessage.Type) *ChatMessageUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *ChatMessageUpdate) SetNillableType(v *chatmessage.Type) *ChatMessageUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetAppID sets the "app_id" field.
func (_u *ChatMessageUpdate) SetAppID(v string) *ChatMessageUpdate {
	_u.mutation.SetAppID(v)
	return _u
}

// SetNillableAppID sets the "app_id" field if the given value is not nil.
func (_u *ChatMessageUpdate) SetNillableAppID(v *string) *ChatMessageUpdate {
	if v != nil {
		_u.SetAppID(*v)
	}
	return _u
}

// ClearAppID clears the value of the "app_id" field.
func (_u *ChatMessageUpdate) ClearAppID() *ChatMessageUpdate {
	_u.mutation.ClearAppID()
	return _u
}

// SetChatSessionID sets the "chat_session_id" field.
func (_u *ChatMessageUpdate) SetChatSessionID(v string) *ChatMessageUpdate {
	_u.mutation.SetChatSessionID(v)
	return _u
}

// SetNillableChatSessionID sets the "chat_session_id" field if the given value is not nil.
func (_u *ChatMessageUpdate) SetNillableChatSessionID(v *string) *ChatMessageUpdate {
	if v != nil {
		_u.SetChatSessionID(*v)
	}
	return _u
}

// ClearChatSessionID clears the value of the "chat_session_id" field.
func (_u *ChatMessageUpdate) ClearChatSessionID() *ChatMessageUpdate {
	_u.mutation.ClearChatSessionID()
	return _u
}

// SetRating sets the "rating" field.
func (_u *ChatMessageUpdate) SetRating(v int) *ChatMessageUpdate {
	_u.mutation.ResetRating()
	_u.mutation.SetRating(v)
	return _u
}

// SetNillableRating sets the "rating" field if the given value is not nil.
func (_u *ChatMessageUpdate) SetNillableRating(v *int) *ChatMessageUpdate {
	if v != nil {
		_u.SetRating(*v)
	}
	return _u
}

// AddRating adds value to the "rating" field.
func (_u *ChatMessageUpdate) AddRating(v int) *ChatMessageUpdate {
	_u.mutation.AddRating(v)
	return _u
}

// ClearRating clears the value of the "rating" field.
func (_u *ChatMessageUpdate) ClearRating() *ChatMessageUpdate {
	_u.mutation.ClearRating()
	return _u
}

// SetReported sets the "reported" field.
func (_u *ChatMessageUpdate) SetReported(v bool) *ChatMessageUpdate {
	_u.mutation.SetReported(v)
	return _u
}

// SetNillableReported sets the "reported" field if the given value is not nil.
func (_u *ChatMessageUpdate) SetNillableReported(v *bool) *ChatMessageUpdate {
	if v != nil {
		_u.SetReported(*v)
	}
	return _u
}

// SetReportReason sets the "report_reason" field.
func (_u *ChatMessageUpdate) SetReportReason(v string) *ChatMessageUpdate {
	_u.mutation.SetReportReason(v)
	return _u
}

// SetNillableReportReason sets the "report_reason" field if the given value is not nil.
func (_u *ChatMessageUpdate) SetNillableReportReason(v *string) *ChatMessageUpdate {
	if v != nil {
		_u.SetReportReason(*v)
	}
	return _u
}

// ClearReportReason clears the value of the "report_reason" field.
func (_u *ChatMessageUpdate) ClearReportReason() *ChatMessageUpdate {
	_u.mutation.ClearReportReason()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ChatMessageUpdate) SetUserID(v int) *ChatMessageUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ChatMessageUpdate) SetNillableUserID(v *int) *ChatMessageUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *ChatMessageUpdate) ClearUserID() *ChatMessageUpdate {
	_u.mutation.ClearUserID()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *ChatMessageUpdate) SetUser(v *User) *ChatMessageUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the ChatMessageMutation object of the builder.
func (_u *ChatMessageUpdate) Mutation() *ChatMessageMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *ChatMessageUpdate) ClearUser() *ChatMessageUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ChatMessageUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChatMessageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ChatMessageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChatMessageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ChatMessageUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := chatmessage.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChatMessageUpdate) check() error {
	if v, ok := _u.mutation.Sender(); ok {
		if err := chatmessage.SenderValidator(v); err != nil {
			return &ValidationError{Name: "sender", err: fmt.Errorf(`ent: validator failed for field "ChatMessage.sender": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := chatmessage.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "ChatMessage.type": %w`, err)}
		}
	}
	return nil
}

func (_u *ChatMessageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(chatmessage.Table, chatmessage.Columns, sqlgraph.NewFieldSpec(chatmessage.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(chatmessage.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExternalID(); ok {
		_spec.SetField(chatmessage.FieldExternalID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Text(); ok {
		_spec.SetField(chatmessage.FieldText, field.TypeString, value)
	}
	if value, ok := _u.mutation.Sender(); ok {
		_spec.SetField(chatmessage.FieldSender, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(chatmessage.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.AppID(); ok {
		_spec.SetField(chatmessage.FieldAppID, field.TypeString, value)
	}
	if _u.mutation.AppIDCleared() {
		_spec.ClearField(chatmessage.FieldAppID, field.TypeString)
	}
	if value, ok := _u.mutation.ChatSessionID(); ok {
		_spec.SetField(chatmessage.FieldChatSessionID, field.TypeString, value)
	}
	if _u.mutation.ChatSessionIDCleared() {
		_spec.ClearField(chatmessage.FieldChatSessionID, field.TypeString)
	}
	if value, ok := _u.mutation.Rating(); ok {
		_spec.SetField(chatmessage.FieldRating, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRating(); ok {
		_spec.AddField(chatmessage.FieldRating, field.TypeInt, value)
	}
	if _u.mutation.RatingCleared() {
		_spec.ClearField(chatmessage.FieldRating, field.TypeInt)
	}
	if value, ok := _u.mutation.Reported(); ok {
		_spec.SetField(chatmessage.FieldReported, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ReportReason(); ok {
		_spec.SetField(chatmessage.FieldReportReason, field.TypeString, value)
	}
	if _u.mutation.ReportReasonCleared() {
		_spec.ClearField(chatmessage.FieldReportReason, field.TypeString)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatmessage.UserTable,
			Columns: []string{chatmessage.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatmessage.UserTable,
			Columns: []string{chatmessage.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{chatmessage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ChatMessageUpdateOne is the builder for updating a single ChatMessage entity.
type ChatMessageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ChatMessageMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ChatMessageUpdateOne) SetUpdatedAt(v time.Time) *ChatMessageUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetExternalID sets the "external_id" field.
func (_u *ChatMessageUpdateOne) SetExternalID(v string) *ChatMessageUpdateOne {
	_u.mutation.SetExternalID(v)
	return _u
}

// SetNillableExternalID sets the "external_id" field if the given value is not nil.
func (_u *ChatMessageUpdateOne) SetNillableExternalID(v *string) *ChatMessageUpdateOne {
	if v != nil {
		_u.SetExternalID(*v)
	}
	return _u
}

// SetText sets the "text" field.
func (_u *ChatMessageUpdateOne) SetText(v string) *ChatMessageUpdateOne {
	_u.mutation.SetText(v)
	return _u
}

// SetNillableText sets the "text" field if the given value is not nil.
func (_u *ChatMessageUpdateOne) SetNillableText(v *string) *ChatMessageUpdateOne {
	if v != nil {
		_u.SetText(*v)
	}
	return _u
}

// SetSender sets the "sender" field.
func (_u *ChatMessageUpdateOne) SetSender(v chatmessage.Sender) *ChatMessageUpdateOne {
	_u.mutation.SetSender(v)
	return _u
}

// SetNillableSender sets the "sender" field if the given value is not nil.
func (_u *ChatMessageUpdateOne) SetNillableSender(v *chatmessage.Sender) *ChatMessageUpdateOne {
	if v != nil {
		_u.SetSender(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *ChatMessageUpdateOne) SetType(v chatmessage.Type) *ChatMessageUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *ChatMessageUpdateOne) SetNillableType(v *chatmessage.Type) *ChatMessageUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetAppID sets the "app_id" field.
func (_u *ChatMessageUpdateOne) SetAppID(v string) *ChatMessageUpdateOne {
	_u.mutation.SetAppID(v)
	return _u
}

// SetNillableAppID sets the "app_id" field if the given value is not nil.
func (_u *ChatMessageUpdateOne) SetNillableAppID(v *string) *ChatMessageUpdateOne {
	if v != nil {
		_u.SetAppID(*v)
	}
	return _u
}

// ClearAppID clears the value of the "app_id" field.
func (_u *ChatMessageUpdateOne) ClearAppID() *ChatMessageUpdateOne {
	_u.mutation.ClearAppID()
	return _u
}

// SetChatSessionID sets the "chat_session_id" field.
func (_u *ChatMessageUpdateOne) SetChatSessionID(v string) *ChatMessageUpdateOne {
	_u.mutation.SetChatSessionID(v)
	return _u
}

// SetNillableChatSessionID sets the "chat_session_id" field if the given value is not nil.
func (_u *ChatMessageUpdateOne) SetNillableChatSessionID(v *string) *ChatMessageUpdateOne {
	if v != nil {
		_u.SetChatSessionID(*v)
	}
	return _u
}

// ClearChatSessionID clears the value of the "chat_session_id" field.
func (_u *ChatMessageUpdateOne) ClearChatSessionID() *ChatMessageUpdateOne {
	_u.mutation.ClearChatSessionID()
	return _u
}

// SetRating sets the "rating" field.
func (_u *ChatMessageUpdateOne) SetRating(v int) *ChatMessageUpdateOne {
	_u.mutation.ResetRating()
	_u.mutation.SetRating(v)
	return _u
}

// SetNillableRating sets the "rating" field if the given value is not nil.
func (_u *ChatMessageUpdateOne) SetNillableRating(v *int) *ChatMessageUpdateOne {
	if v != nil {
		_u.SetRating(*v)
	}
	return _u
}

// AddRating adds value to the "rating" field.
func (_u *ChatMessageUpdateOne) AddRating(v int) *ChatMessageUpdateOne {
	_u.mutation.AddRating(v)
	return _u
}

// ClearRating clears the value of the "rating" field.
func (_u *ChatMessageUpdateOne) ClearRating() *ChatMessageUpdateOne {
	_u.mutation.ClearRating()
	return _u
}

// SetReported sets the "reported" field.
func (_u *ChatMessageUpdateOne) SetReported(v bool) *ChatMessageUpdateOne {
	_u.mutation.SetReported(v)
	return _u
}

// SetNillableReported sets the "reported" field if the given value is not nil.
func (_u *ChatMessageUpdateOne) SetNillableReported(v *bool) *ChatMessageUpdateOne {
	if v != nil {
		_u.SetReported(*v)
	}
	return _u
}

// SetReportReason sets the "report_reason" field.
func (_u *ChatMessageUpdateOne) SetReportReason(v string) *ChatMessageUpdateOne {
	_u.mutation.SetReportReason(v)
	return _u
}

// SetNillableReportReason sets the "report_reason" field if the given value is not nil.
func (_u *ChatMessageUpdateOne) SetNillableReportReason(v *string) *ChatMessageUpdateOne {
	if v != nil {
		_u.SetReportReason(*v)
	}
	return _u
}

// ClearReportReason clears the value of the "report_reason" field.
func (_u *ChatMessageUpdateOne) ClearReportReason() *ChatMessageUpdateOne {
	_u.mutation.ClearReportReason()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ChatMessageUpdateOne) SetUserID(v int) *ChatMessageUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ChatMessageUpdateOne) SetNillableUserID(v *int) *ChatMessageUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *ChatMessageUpdateOne) ClearUserID() *ChatMessageUpdateOne {
	_u.mutation.ClearUserID()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *ChatMessageUpdateOne) SetUser(v *User) *ChatMessageUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the ChatMessageMutation object of the builder.
func (_u *ChatMessageUpdateOne) Mutation() *ChatMessageMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *ChatMessageUpdateOne) ClearUser() *ChatMessageUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the ChatMessageUpdate builder.
func (_u *ChatMessageUpdateOne) Where(ps ...predicate.ChatMessage) *ChatMessageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ChatMessageUpdateOne) Select(field string, fields ...string) *ChatMessageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ChatMessage entity.
func (_u *ChatMessageUpdateOne) Save(ctx context.Context) (*ChatMessage, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChatMessageUpdateOne) SaveX(ctx context.Context) *ChatMessage {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ChatMessageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChatMessageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ChatMessageUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := chatmessage.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChatMessageUpdateOne) check() error {
	if v, ok := _u.mutation.Sender(); ok {
		if err := chatmessage.SenderValidator(v); err != nil {
			return &ValidationError{Name: "sender", err: fmt.Errorf(`ent: validator failed for field "ChatMessage.sender": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := chatmessage.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "ChatMessage.type": %w`, err)}
		}
	}
	return nil
}

func (_u *ChatMessageUpdateOne) sqlSave(ctx context.Context) (_node *ChatMessage, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(chatmessage.Table, chatmessage.Columns, sqlgraph.NewFieldSpec(chatmessage.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ChatMessage.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, chatmessage.FieldID)
		for _, f := range fields {
			if !chatmessage.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != chatmessage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(chatmessage.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExternalID(); ok {
		_spec.SetField(chatmessage.FieldExternalID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Text(); ok {
		_spec.SetField(chatmessage.FieldText, field.TypeString, value)
	}
	if value, ok := _u.mutation.Sender(); ok {
		_spec.SetField(chatmessage.FieldSender, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(chatmessage.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.AppID(); ok {
		_spec.SetField(chatmessage.FieldAppID, field.TypeString, value)
	}
	if _u.mutation.AppIDCleared() {
		_spec.ClearField(chatmessage.FieldAppID, field.TypeString)
	}
	if value, ok := _u.mutation.ChatSessionID(); ok {
		_spec.SetField(chatmessage.FieldChatSessionID, field.TypeString, value)
	}
	if _u.mutation.ChatSessionIDCleared() {
		_spec.ClearField(chatmessage.FieldChatSessionID, field.TypeString)
	}
	if value, ok := _u.mutation.Rating(); ok {
		_spec.SetField(chatmessage.FieldRating, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRating(); ok {
		_spec.AddField(chatmessage.FieldRating, field.TypeInt, value)
	}
	if _u.mutation.RatingCleared() {
		_spec.ClearField(chatmessage.FieldRating, field.TypeInt)
	}
	if value, ok := _u.mutation.Reported(); ok {
		_spec.SetField(chatmessage.FieldReported, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ReportReason(); ok {
		_spec.SetField(chatmessage.FieldReportReason, field.TypeString, value)
	}
	if _u.mutation.ReportReasonCleared() {
		_spec.ClearField(chatmessage.FieldReportReason, field.TypeString)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatmessage.UserTable,
			Columns: []string{chatmessage.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatmessage.UserTable,
			Columns: []string{chatmessage.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ChatMessage{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{chatmessage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
