// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"remi/server/ent/conversation"
	"remi/server/ent/device"
	"remi/server/ent/folder"
	"remi/server/ent/user"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Conversation is the model entity for the Conversation schema.
type Conversation struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Summary holds the value of the "summary" field.
	Summary string `json:"summary,omitempty"`
	// Visibility holds the value of the "visibility" field.
	Visibility string `json:"visibility,omitempty"`
	// Starred holds the value of the "starred" field.
	Starred bool `json:"starred,omitempty"`
	// StartedAt holds the value of the "started_at" field.
	StartedAt time.Time `json:"started_at,omitempty"`
	// EndedAt holds the value of the "ended_at" field.
	EndedAt *time.Time `json:"ended_at,omitempty"`
	// Status holds the value of the "status" field.
	Status conversation.Status `json:"status,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID *int `json:"user_id,omitempty"`
	// DeviceID holds the value of the "device_id" field.
	DeviceID *int `json:"device_id,omitempty"`
	// FolderID holds the value of the "folder_id" field.
	FolderID *int `json:"folder_id,omitempty"`
	// AudioFiles holds the value of the "audio_files" field.
	AudioFiles []map[string]interface{} `json:"audio_files,omitempty"`
	// ConversationAudio holds the value of the "conversation_audio" field.
	ConversationAudio map[string]interface{} `json:"conversation_audio,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ConversationQuery when eager-loading is set.
	Edges        ConversationEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ConversationEdges holds the relations/edges for other nodes in the graph.
type ConversationEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Device holds the value of the device edge.
	Device *Device `json:"device,omitempty"`
	// Folder holds the value of the folder edge.
	Folder *Folder `json:"folder,omitempty"`
	// TranscriptSegments holds the value of the transcript_segments edge.
	TranscriptSegments []*TranscriptSegment `json:"transcript_segments,omitempty"`
	// Memories holds the value of the memories edge.
	Memories []*Memory `json:"memories,omitempty"`
	// Todos holds the value of the todos edge.
	Todos []*Todo `json:"todos,omitempty"`
	// ActionItems holds the value of the action_items edge.
	ActionItems []*ActionItem `json:"action_items,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [7]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ConversationEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// DeviceOrErr returns the Device value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ConversationEdges) DeviceOrErr() (*Device, error) {
	if e.Device != nil {
		return e.Device, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: device.Label}
	}
	return nil, &NotLoadedError{edge: "device"}
}

// FolderOrErr returns the Folder value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ConversationEdges) FolderOrErr() (*Folder, error) {
	if e.Folder != nil {
		return e.Folder, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: folder.Label}
	}
	return nil, &NotLoadedError{edge: "folder"}
}

// TranscriptSegmentsOrErr returns the TranscriptSegments value or an error if the edge
// was not loaded in eager-loading.
func (e ConversationEdges) TranscriptSegmentsOrErr() ([]*TranscriptSegment, error) {
	if e.loadedTypes[3] {
		return e.TranscriptSegments, nil
	}
	return nil, &NotLoadedError{edge: "transcript_segments"}
}

// MemoriesOrErr returns the Memories value or an error if the edge
// was not loaded in eager-loading.
func (e ConversationEdges) MemoriesOrErr() ([]*Memory, error) {
	if e.loadedTypes[4] {
		return e.Memories, nil
	}
	return nil, &NotLoadedError{edge: "memories"}
}

// TodosOrErr returns the Todos value or an error if the edge
// was not loaded in eager-loading.
func (e ConversationEdges) TodosOrErr() ([]*Todo, error) {
	if e.loadedTypes[5] {
		return e.Todos, nil
	}
	return nil, &NotLoadedError{edge: "todos"}
}

// ActionItemsOrErr returns the ActionItems value or an error if the edge
// was not loaded in eager-loading.
func (e ConversationEdges) ActionItemsOrErr() ([]*ActionItem, error) {
	if e.loadedTypes[6] {
		return e.ActionItems, nil
	}
	return nil, &NotLoadedError{edge: "action_items"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Conversation) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case conversation.FieldAudioFiles, conversation.FieldConversationAudio:
			values[i] = new([]byte)
		case conversation.FieldStarred:
			values[i] = new(sql.NullBool)
		case conversation.FieldID, conversation.FieldUserID, conversation.FieldDeviceID, conversation.FieldFolderID:
			values[i] = new(sql.NullInt64)
		case conversation.FieldTitle, conversation.FieldSummary, conversation.FieldVisibility, conversation.FieldStatus:
			values[i] = new(sql.NullString)
		case conversation.FieldCreatedAt, conversation.FieldUpdatedAt, conversation.FieldStartedAt, conversation.FieldEndedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Conversation fields.
func (_m *Conversation) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case conversation.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case conversation.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case conversation.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case conversation.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case conversation.FieldSummary:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field summary", values[i])
			} else if value.Valid {
				_m.Summary = value.String
			}
		case conversation.FieldVisibility:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field visibility", values[i])
			} else if value.Valid {
				_m.Visibility = value.String
			}
		case conversation.FieldStarred:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field starred", values[i])
			} else if value.Valid {
				_m.Starred = value.Bool
			}
		case conversation.FieldStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
			} else if value.Valid {
				_m.StartedAt = value.Time
			}
		case conversation.FieldEndedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field ended_at", values[i])
			} else if value.Valid {
				_m.EndedAt = new(time.Time)
				*_m.EndedAt = value.Time
			}
		case conversation.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = conversation.Status(value.String)
			}
		case conversation.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = new(int)
				*_m.UserID = int(value.Int64)
			}
		case conversation.FieldDeviceID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field device_id", values[i])
			} else if value.Valid {
				_m.DeviceID = new(int)
				*_m.DeviceID = int(value.Int64)
			}
		case conversation.FieldFolderID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field folder_id", values[i])
			} else if value.Valid {
				_m.FolderID = new(int)
				*_m.FolderID = int(value.Int64)
			}
		case conversation.FieldAudioFiles:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field audio_files", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.AudioFiles); err != nil {
					return fmt.Errorf("unmarshal field audio_files: %w", err)
				}
			}
		case conversation.FieldConversationAudio:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field conversation_audio", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ConversationAudio); err != nil {
					return fmt.Errorf("unmarshal field conversation_audio: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Conversation.
// This includes values selected through modifiers, order, etc.
func (_m *Conversation) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the Conversation entity.
func (_m *Conversation) QueryUser() *UserQuery {
	return NewConversationClient(_m.config).QueryUser(_m)
}

// QueryDevice queries the "device" edge of the Conversation entity.
func (_m *Conversation) QueryDevice() *DeviceQuery {
	return NewConversationClient(_m.config).QueryDevice(_m)
}

// QueryFolder queries the "folder" edge of the Conversation entity.
func (_m *Conversation) QueryFolder() *FolderQuery {
	return NewConversationClient(_m.config).QueryFolder(_m)
}

// QueryTranscriptSegments queries the "transcript_segments" edge of the Conversation entity.
func (_m *Conversation) QueryTranscriptSegments() *TranscriptSegmentQuery {
	return NewConversationClient(_m.config).QueryTranscriptSegments(_m)
}

// QueryMemories queries the "memories" edge of the Conversation entity.
func (_m *Conversation) QueryMemories() *MemoryQuery {
	return NewConversationClient(_m.config).QueryMemories(_m)
}

// QueryTodos queries the "todos" edge of the Conversation entity.
func (_m *Conversation) QueryTodos() *TodoQuery {
	return NewConversationClient(_m.config).QueryTodos(_m)
}

// QueryActionItems queries the "action_items" edge of the Conversation entity.
func (_m *Conversation) QueryActionItems() *ActionItemQuery {
	return NewConversationClient(_m.config).QueryActionItems(_m)
}

// Update returns a builder for updating this Conversation.
// Note that you need to call Conversation.Unwrap() before calling this method if this Conversation
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Conversation) Update() *ConversationUpdateOne {
	return NewConversationClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Conversation entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Conversation) Unwrap() *Conversation {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Conversation is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Conversation) String() string {
	var builder strings.Builder
	builder.WriteString("Conversation(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("summary=")
	builder.WriteString(_m.Summary)
	builder.WriteString(", ")
	builder.WriteString("visibility=")
	builder.WriteString(_m.Visibility)
	builder.WriteString(", ")
	builder.WriteString("starred=")
	builder.WriteString(fmt.Sprintf("%v", _m.Starred))
	builder.WriteString(", ")
	builder.WriteString("started_at=")
	builder.WriteString(_m.StartedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.EndedAt; v != nil {
		builder.WriteString("ended_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	if v := _m.UserID; v != nil {
		builder.WriteString("user_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.DeviceID; v != nil {
		builder.WriteString("device_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.FolderID; v != nil {
		builder.WriteString("folder_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("audio_files=")
	builder.WriteString(fmt.Sprintf("%v", _m.AudioFiles))
	builder.WriteString(", ")
	builder.WriteString("conversation_audio=")
	builder.WriteString(fmt.Sprintf("%v", _m.ConversationAudio))
	builder.WriteByte(')')
	return builder.String()
}

// Conversations is a parsable slice of Conversation.
type Conversations []*Conversation
