// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"remi/server/ent/actionitem"
	"remi/server/ent/conversation"
	"remi/server/ent/device"
	"remi/server/ent/memory"
	"remi/server/ent/todo"
	"remi/server/ent/transcriptsegment"
	"remi/server/ent/user"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ConversationCreate is the builder for creating a Conversation entity.
type ConversationCreate struct {
	config
	mutation *ConversationMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *ConversationCreate) SetCreatedAt(v time.Time) *ConversationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ConversationCreate) SetNillableCreatedAt(v *time.Time) *ConversationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ConversationCreate) SetUpdatedAt(v time.Time) *ConversationCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ConversationCreate) SetNillableUpdatedAt(v *time.Time) *ConversationCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetTitle sets the "title" field.
func (_c *ConversationCreate) SetTitle(v string) *ConversationCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_c *ConversationCreate) SetNillableTitle(v *string) *ConversationCreate {
	if v != nil {
		_c.SetTitle(*v)
	}
	return _c
}

// SetSummary sets the "summary" field.
func (_c *ConversationCreate) SetSummary(v string) *ConversationCreate {
	_c.mutation.SetSummary(v)
	return _c
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_c *ConversationCreate) SetNillableSummary(v *string) *ConversationCreate {
	if v != nil {
		_c.SetSummary(*v)
	}
	return _c
}

// SetStartedAt sets the "started_at" field.
func (_c *ConversationCreate) SetStartedAt(v time.Time) *ConversationCreate {
	_c.mutation.SetStartedAt(v)
	return _c
}

// SetEndedAt sets the "ended_at" field.
func (_c *ConversationCreate) SetEndedAt(v time.Time) *ConversationCreate {
	_c.mutation.SetEndedAt(v)
	return _c
}

// SetNillableEndedAt sets the "ended_at" field if the given value is not nil.
func (_c *ConversationCreate) SetNillableEndedAt(v *time.Time) *ConversationCreate {
	if v != nil {
		_c.SetEndedAt(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *ConversationCreate) SetStatus(v conversation.Status) *ConversationCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ConversationCreate) SetNillableStatus(v *conversation.Status) *ConversationCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_c *ConversationCreate) SetUserID(id int) *ConversationCreate {
	_c.mutation.SetUserID(id)
	return _c
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (_c *ConversationCreate) SetNillableUserID(id *int) *ConversationCreate {
	if id != nil {
		_c = _c.SetUserID(*id)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *ConversationCreate) SetUser(v *User) *ConversationCreate {
	return _c.SetUserID(v.ID)
}

// SetDeviceID sets the "device" edge to the Device entity by ID.
func (_c *ConversationCreate) SetDeviceID(id int) *ConversationCreate {
	_c.mutation.SetDeviceID(id)
	return _c
}

// SetNillableDeviceID sets the "device" edge to the Device entity by ID if the given value is not nil.
func (_c *ConversationCreate) SetNillableDeviceID(id *int) *ConversationCreate {
	if id != nil {
		_c = _c.SetDeviceID(*id)
	}
	return _c
}

// SetDevice sets the "device" edge to the Device entity.
func (_c *ConversationCreate) SetDevice(v *Device) *ConversationCreate {
	return _c.SetDeviceID(v.ID)
}

// AddTranscriptSegmentIDs adds the "transcript_segments" edge to the TranscriptSegment entity by IDs.
func (_c *ConversationCreate) AddTranscriptSegmentIDs(ids ...int) *ConversationCreate {
	_c.mutation.AddTranscriptSegmentIDs(ids...)
	return _c
}

// AddTranscriptSegments adds the "transcript_segments" edges to the TranscriptSegment entity.
func (_c *ConversationCreate) AddTranscriptSegments(v ...*TranscriptSegment) *ConversationCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTranscriptSegmentIDs(ids...)
}

// AddMemoryIDs adds the "memories" edge to the Memory entity by IDs.
func (_c *ConversationCreate) AddMemoryIDs(ids ...int) *ConversationCreate {
	_c.mutation.AddMemoryIDs(ids...)
	return _c
}

// AddMemories adds the "memories" edges to the Memory entity.
func (_c *ConversationCreate) AddMemories(v ...*Memory) *ConversationCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMemoryIDs(ids...)
}

// AddTodoIDs adds the "todos" edge to the Todo entity by IDs.
func (_c *ConversationCreate) AddTodoIDs(ids ...int) *ConversationCreate {
	_c.mutation.AddTodoIDs(ids...)
	return _c
}

// AddTodos adds the "todos" edges to the Todo entity.
func (_c *ConversationCreate) AddTodos(v ...*Todo) *ConversationCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTodoIDs(ids...)
}

// AddActionItemIDs adds the "action_items" edge to the ActionItem entity by IDs.
func (_c *ConversationCreate) AddActionItemIDs(ids ...int) *ConversationCreate {
	_c.mutation.AddActionItemIDs(ids...)
	return _c
}

// AddActionItems adds the "action_items" edges to the ActionItem entity.
func (_c *ConversationCreate) AddActionItems(v ...*ActionItem) *ConversationCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddActionItemIDs(ids...)
}

// Mutation returns the ConversationMutation object of the builder.
func (_c *ConversationCreate) Mutation() *ConversationMutation {
	return _c.mutation
}

// Save creates the Conversation in the database.
func (_c *ConversationCreate) Save(ctx context.Context) (*Conversation, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ConversationCreate) SaveX(ctx context.Context) *Conversation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ConversationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ConversationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ConversationCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := conversation.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := conversation.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Title(); !ok {
		v := conversation.DefaultTitle
		_c.mutation.SetTitle(v)
	}
	if _, ok := _c.mutation.Summary(); !ok {
		v := conversation.DefaultSummary
		_c.mutation.SetSummary(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := conversation.DefaultStatus
		_c.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ConversationCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Conversation.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Conversation.updated_at"`)}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Conversation.title"`)}
	}
	if _, ok := _c.mutation.Summary(); !ok {
		return &ValidationError{Name: "summary", err: errors.New(`ent: missing required field "Conversation.summary"`)}
	}
	if _, ok := _c.mutation.StartedAt(); !ok {
		return &ValidationError{Name: "started_at", err: errors.New(`ent: missing required field "Conversation.started_at"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Conversation.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := conversation.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Conversation.status": %w`, err)}
		}
	}
	return nil
}

func (_c *ConversationCreate) sqlSave(ctx context.Context) (*Conversation, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ConversationCreate) createSpec() (*Conversation, *sqlgraph.CreateSpec) {
	var (
		_node = &Conversation{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(conversation.Table, sqlgraph.NewFieldSpec(conversation.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(conversation.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(conversation.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(conversation.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Summary(); ok {
		_spec.SetField(conversation.FieldSummary, field.TypeString, value)
		_node.Summary = value
	}
	if value, ok := _c.mutation.StartedAt(); ok {
		_spec.SetField(conversation.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = value
	}
	if value, ok := _c.mutation.EndedAt(); ok {
		_spec.SetField(conversation.FieldEndedAt, field.TypeTime, value)
		_node.EndedAt = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(conversation.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   conversation.UserTable,
			Columns: []string{conversation.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_conversations = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.DeviceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   conversation.DeviceTable,
			Columns: []string{conversation.DeviceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(device.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.device_conversations = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TranscriptSegmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   conversation.TranscriptSegmentsTable,
			Columns: []string{conversation.TranscriptSegmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transcriptsegment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.MemoriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   conversation.MemoriesTable,
			Columns: []string{conversation.MemoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(memory.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TodosIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   conversation.TodosTable,
			Columns: []string{conversation.TodosColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(todo.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ActionItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   conversation.ActionItemsTable,
			Columns: []string{conversation.ActionItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(actionitem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ConversationCreateBulk is the builder for creating many Conversation entities in bulk.
type ConversationCreateBulk struct {
	config
	err      error
	builders []*ConversationCreate
}

// Save creates the Conversation entities in the database.
func (_c *ConversationCreateBulk) Save(ctx context.Context) ([]*Conversation, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Conversation, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ConversationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ConversationCreateBulk) SaveX(ctx context.Context) []*Conversation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ConversationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ConversationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
