// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"remi/server/ent/conversation"
	"remi/server/ent/device"
	"remi/server/ent/predicate"
	"remi/server/ent/user"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DeviceUpdate is the builder for updating Device entities.
type DeviceUpdate struct {
	config
	hooks    []Hook
	mutation *DeviceMutation
}

// Where appends a list predicates to the DeviceUpdate builder.
func (_u *DeviceUpdate) Where(ps ...predicate.Device) *DeviceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DeviceUpdate) SetUpdatedAt(v time.Time) *DeviceUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeviceID sets the "device_id" field.
func (_u *DeviceUpdate) SetDeviceID(v string) *DeviceUpdate {
	_u.mutation.SetDeviceID(v)
	return _u
}

// SetNillableDeviceID sets the "device_id" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableDeviceID(v *string) *DeviceUpdate {
	if v != nil {
		_u.SetDeviceID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *DeviceUpdate) SetName(v string) *DeviceUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableName(v *string) *DeviceUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetFirmwareVersion sets the "firmware_version" field.
func (_u *DeviceUpdate) SetFirmwareVersion(v string) *DeviceUpdate {
	_u.mutation.SetFirmwareVersion(v)
	return _u
}

// SetNillableFirmwareVersion sets the "firmware_version" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableFirmwareVersion(v *string) *DeviceUpdate {
	if v != nil {
		_u.SetFirmwareVersion(*v)
	}
	return _u
}

// SetBatteryLevel sets the "battery_level" field.
func (_u *DeviceUpdate) SetBatteryLevel(v int) *DeviceUpdate {
	_u.mutation.ResetBatteryLevel()
	_u.mutation.SetBatteryLevel(v)
	return _u
}

// SetNillableBatteryLevel sets the "battery_level" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableBatteryLevel(v *int) *DeviceUpdate {
	if v != nil {
		_u.SetBatteryLevel(*v)
	}
	return _u
}

// AddBatteryLevel adds value to the "battery_level" field.
func (_u *DeviceUpdate) AddBatteryLevel(v int) *DeviceUpdate {
	_u.mutation.AddBatteryLevel(v)
	return _u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_u *DeviceUpdate) SetLastSeenAt(v time.Time) *DeviceUpdate {
	_u.mutation.SetLastSeenAt(v)
	return _u
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableLastSeenAt(v *time.Time) *DeviceUpdate {
	if v != nil {
		_u.SetLastSeenAt(*v)
	}
	return _u
}

// ClearLastSeenAt clears the value of the "last_seen_at" field.
func (_u *DeviceUpdate) ClearLastSeenAt() *DeviceUpdate {
	_u.mutation.ClearLastSeenAt()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *DeviceUpdate) SetUserID(v int) *DeviceUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableUserID(v *int) *DeviceUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *DeviceUpdate) ClearUserID() *DeviceUpdate {
	_u.mutation.ClearUserID()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *DeviceUpdate) SetUser(v *User) *DeviceUpdate {
	return _u.SetUserID(v.ID)
}

// AddConversationIDs adds the "conversations" edge to the Conversation entity by IDs.
func (_u *DeviceUpdate) AddConversationIDs(ids ...int) *DeviceUpdate {
	_u.mutation.AddConversationIDs(ids...)
	return _u
}

// AddConversations adds the "conversations" edges to the Conversation entity.
func (_u *DeviceUpdate) AddConversations(v ...*Conversation) *DeviceUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddConversationIDs(ids...)
}

// Mutation returns the DeviceMutation object of the builder.
func (_u *DeviceUpdate) Mutation() *DeviceMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *DeviceUpdate) ClearUser() *DeviceUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearConversations clears all "conversations" edges to the Conversation entity.
func (_u *DeviceUpdate) ClearConversations() *DeviceUpdate {
	_u.mutation.ClearConversations()
	return _u
}

// RemoveConversationIDs removes the "conversations" edge to Conversation entities by IDs.
func (_u *DeviceUpdate) RemoveConversationIDs(ids ...int) *DeviceUpdate {
	_u.mutation.RemoveConversationIDs(ids...)
	return _u
}

// RemoveConversations removes "conversations" edges to Conversation entities.
func (_u *DeviceUpdate) RemoveConversations(v ...*Conversation) *DeviceUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveConversationIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DeviceUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DeviceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DeviceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DeviceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DeviceUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := device.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DeviceUpdate) check() error {
	if v, ok := _u.mutation.DeviceID(); ok {
		if err := device.DeviceIDValidator(v); err != nil {
			return &ValidationError{Name: "device_id", err: fmt.Errorf(`ent: validator failed for field "Device.device_id": %w`, err)}
		}
	}
	return nil
}

func (_u *DeviceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(device.Table, device.Columns, sqlgraph.NewFieldSpec(device.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(device.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeviceID(); ok {
		_spec.SetField(device.FieldDeviceID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(device.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.FirmwareVersion(); ok {
		_spec.SetField(device.FieldFirmwareVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.BatteryLevel(); ok {
		_spec.SetField(device.FieldBatteryLevel, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedBatteryLevel(); ok {
		_spec.AddField(device.FieldBatteryLevel, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastSeenAt(); ok {
		_spec.SetField(device.FieldLastSeenAt, field.TypeTime, value)
	}
	if _u.mutation.LastSeenAtCleared() {
		_spec.ClearField(device.FieldLastSeenAt, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   device.UserTable,
			Columns: []string{device.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   device.UserTable,
			Columns: []string{device.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ConversationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   device.ConversationsTable,
			Columns: []string{device.ConversationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversation.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedConversationsIDs(); len(nodes) > 0 && !_u.mutation.ConversationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   device.ConversationsTable,
			Columns: []string{device.ConversationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ConversationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   device.ConversationsTable,
			Columns: []string{device.ConversationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{device.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DeviceUpdateOne is the builder for updating a single Device entity.
type DeviceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DeviceMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DeviceUpdateOne) SetUpdatedAt(v time.Time) *DeviceUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeviceID sets the "device_id" field.
func (_u *DeviceUpdateOne) SetDeviceID(v string) *DeviceUpdateOne {
	_u.mutation.SetDeviceID(v)
	return _u
}

// SetNillableDeviceID sets the "device_id" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableDeviceID(v *string) *DeviceUpdateOne {
	if v != nil {
		_u.SetDeviceID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *DeviceUpdateOne) SetName(v string) *DeviceUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableName(v *string) *DeviceUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetFirmwareVersion sets the "firmware_version" field.
func (_u *DeviceUpdateOne) SetFirmwareVersion(v string) *DeviceUpdateOne {
	_u.mutation.SetFirmwareVersion(v)
	return _u
}

// SetNillableFirmwareVersion sets the "firmware_version" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableFirmwareVersion(v *string) *DeviceUpdateOne {
	if v != nil {
		_u.SetFirmwareVersion(*v)
	}
	return _u
}

// SetBatteryLevel sets the "battery_level" field.
func (_u *DeviceUpdateOne) SetBatteryLevel(v int) *DeviceUpdateOne {
	_u.mutation.ResetBatteryLevel()
	_u.mutation.SetBatteryLevel(v)
	return _u
}

// SetNillableBatteryLevel sets the "battery_level" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableBatteryLevel(v *int) *DeviceUpdateOne {
	if v != nil {
		_u.SetBatteryLevel(*v)
	}
	return _u
}

// AddBatteryLevel adds value to the "battery_level" field.
func (_u *DeviceUpdateOne) AddBatteryLevel(v int) *DeviceUpdateOne {
	_u.mutation.AddBatteryLevel(v)
	return _u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_u *DeviceUpdateOne) SetLastSeenAt(v time.Time) *DeviceUpdateOne {
	_u.mutation.SetLastSeenAt(v)
	return _u
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableLastSeenAt(v *time.Time) *DeviceUpdateOne {
	if v != nil {
		_u.SetLastSeenAt(*v)
	}
	return _u
}

// ClearLastSeenAt clears the value of the "last_seen_at" field.
func (_u *DeviceUpdateOne) ClearLastSeenAt() *DeviceUpdateOne {
	_u.mutation.ClearLastSeenAt()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *DeviceUpdateOne) SetUserID(v int) *DeviceUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableUserID(v *int) *DeviceUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *DeviceUpdateOne) ClearUserID() *DeviceUpdateOne {
	_u.mutation.ClearUserID()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *DeviceUpdateOne) SetUser(v *User) *DeviceUpdateOne {
	return _u.SetUserID(v.ID)
}

// AddConversationIDs adds the "conversations" edge to the Conversation entity by IDs.
func (_u *DeviceUpdateOne) AddConversationIDs(ids ...int) *DeviceUpdateOne {
	_u.mutation.AddConversationIDs(ids...)
	return _u
}

// AddConversations adds the "conversations" edges to the Conversation entity.
func (_u *DeviceUpdateOne) AddConversations(v ...*Conversation) *DeviceUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddConversationIDs(ids...)
}

// Mutation returns the DeviceMutation object of the builder.
func (_u *DeviceUpdateOne) Mutation() *DeviceMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *DeviceUpdateOne) ClearUser() *DeviceUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearConversations clears all "conversations" edges to the Conversation entity.
func (_u *DeviceUpdateOne) ClearConversations() *DeviceUpdateOne {
	_u.mutation.ClearConversations()
	return _u
}

// RemoveConversationIDs removes the "conversations" edge to Conversation entities by IDs.
func (_u *DeviceUpdateOne) RemoveConversationIDs(ids ...int) *DeviceUpdateOne {
	_u.mutation.RemoveConversationIDs(ids...)
	return _u
}

// RemoveConversations removes "conversations" edges to Conversation entities.
func (_u *DeviceUpdateOne) RemoveConversations(v ...*Conversation) *DeviceUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveConversationIDs(ids...)
}

// Where appends a list predicates to the DeviceUpdate builder.
func (_u *DeviceUpdateOne) Where(ps ...predicate.Device) *DeviceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DeviceUpdateOne) Select(field string, fields ...string) *DeviceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Device entity.
func (_u *DeviceUpdateOne) Save(ctx context.Context) (*Device, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DeviceUpdateOne) SaveX(ctx context.Context) *Device {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DeviceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DeviceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DeviceUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := device.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DeviceUpdateOne) check() error {
	if v, ok := _u.mutation.DeviceID(); ok {
		if err := device.DeviceIDValidator(v); err != nil {
			return &ValidationError{Name: "device_id", err: fmt.Errorf(`ent: validator failed for field "Device.device_id": %w`, err)}
		}
	}
	return nil
}

func (_u *DeviceUpdateOne) sqlSave(ctx context.Context) (_node *Device, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(device.Table, device.Columns, sqlgraph.NewFieldSpec(device.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Device.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, device.FieldID)
		for _, f := range fields {
			if !device.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != device.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(device.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeviceID(); ok {
		_spec.SetField(device.FieldDeviceID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(device.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.FirmwareVersion(); ok {
		_spec.SetField(device.FieldFirmwareVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.BatteryLevel(); ok {
		_spec.SetField(device.FieldBatteryLevel, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedBatteryLevel(); ok {
		_spec.AddField(device.FieldBatteryLevel, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastSeenAt(); ok {
		_spec.SetField(device.FieldLastSeenAt, field.TypeTime, value)
	}
	if _u.mutation.LastSeenAtCleared() {
		_spec.ClearField(device.FieldLastSeenAt, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   device.UserTable,
			Columns: []string{device.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   device.UserTable,
			Columns: []string{device.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ConversationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   device.ConversationsTable,
			Columns: []string{device.ConversationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversation.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedConversationsIDs(); len(nodes) > 0 && !_u.mutation.ConversationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   device.ConversationsTable,
			Columns: []string{device.ConversationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ConversationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   device.ConversationsTable,
			Columns: []string{device.ConversationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Device{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{device.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
