// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"remi/server/ent/notificationtoken"
	"remi/server/ent/user"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// NotificationTokenCreate is the builder for creating a NotificationToken entity.
type NotificationTokenCreate struct {
	config
	mutation *NotificationTokenMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *NotificationTokenCreate) SetCreatedAt(v time.Time) *NotificationTokenCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *NotificationTokenCreate) SetNillableCreatedAt(v *time.Time) *NotificationTokenCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *NotificationTokenCreate) SetUpdatedAt(v time.Time) *NotificationTokenCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *NotificationTokenCreate) SetNillableUpdatedAt(v *time.Time) *NotificationTokenCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetToken sets the "token" field.
func (_c *NotificationTokenCreate) SetToken(v string) *NotificationTokenCreate {
	_c.mutation.SetToken(v)
	return _c
}

// SetPlatform sets the "platform" field.
func (_c *NotificationTokenCreate) SetPlatform(v string) *NotificationTokenCreate {
	_c.mutation.SetPlatform(v)
	return _c
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_c *NotificationTokenCreate) SetNillablePlatform(v *string) *NotificationTokenCreate {
	if v != nil {
		_c.SetPlatform(*v)
	}
	return _c
}

// SetDeviceKey sets the "device_key" field.
func (_c *NotificationTokenCreate) SetDeviceKey(v string) *NotificationTokenCreate {
	_c.mutation.SetDeviceKey(v)
	return _c
}

// SetNillableDeviceKey sets the "device_key" field if the given value is not nil.
func (_c *NotificationTokenCreate) SetNillableDeviceKey(v *string) *NotificationTokenCreate {
	if v != nil {
		_c.SetDeviceKey(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *NotificationTokenCreate) SetUserID(v int) *NotificationTokenCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_c *NotificationTokenCreate) SetNillableUserID(v *int) *NotificationTokenCreate {
	if v != nil {
		_c.SetUserID(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *NotificationTokenCreate) SetUser(v *User) *NotificationTokenCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the NotificationTokenMutation object of the builder.
func (_c *NotificationTokenCreate) Mutation() *NotificationTokenMutation {
	return _c.mutation
}

// Save creates the NotificationToken in the database.
func (_c *NotificationTokenCreate) Save(ctx context.Context) (*NotificationToken, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *NotificationTokenCreate) SaveX(ctx context.Context) *NotificationToken {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NotificationTokenCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NotificationTokenCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *NotificationTokenCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := notificationtoken.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := notificationtoken.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Platform(); !ok {
		v := notificationtoken.DefaultPlatform
		_c.mutation.SetPlatform(v)
	}
	if _, ok := _c.mutation.DeviceKey(); !ok {
		v := notificationtoken.DefaultDeviceKey
		_c.mutation.SetDeviceKey(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *NotificationTokenCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "NotificationToken.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "NotificationToken.updated_at"`)}
	}
	if _, ok := _c.mutation.Token(); !ok {
		return &ValidationError{Name: "token", err: errors.New(`ent: missing required field "NotificationToken.token"`)}
	}
	if v, ok := _c.mutation.Token(); ok {
		if err := notificationtoken.TokenValidator(v); err != nil {
			return &ValidationError{Name: "token", err: fmt.Errorf(`ent: validator failed for field "NotificationToken.token": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Platform(); !ok {
		return &ValidationError{Name: "platform", err: errors.New(`ent: missing required field "NotificationToken.platform"`)}
	}
	if _, ok := _c.mutation.DeviceKey(); !ok {
		return &ValidationError{Name: "device_key", err: errors.New(`ent: missing required field "NotificationToken.device_key"`)}
	}
	return nil
}

func (_c *NotificationTokenCreate) sqlSave(ctx context.Context) (*NotificationToken, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *NotificationTokenCreate) createSpec() (*NotificationToken, *sqlgraph.CreateSpec) {
	var (
		_node = &NotificationToken{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(notificationtoken.Table, sqlgraph.NewFieldSpec(notificationtoken.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(notificationtoken.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(notificationtoken.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Token(); ok {
		_spec.SetField(notificationtoken.FieldToken, field.TypeString, value)
		_node.Token = value
	}
	if value, ok := _c.mutation.Platform(); ok {
		_spec.SetField(notificationtoken.FieldPlatform, field.TypeString, value)
		_node.Platform = value
	}
	if value, ok := _c.mutation.DeviceKey(); ok {
		_spec.SetField(notificationtoken.FieldDeviceKey, field.TypeString, value)
		_node.DeviceKey = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notificationtoken.UserTable,
			Columns: []string{notificationtoken.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// NotificationTokenCreateBulk is the builder for creating many NotificationToken entities in bulk.
type NotificationTokenCreateBulk struct {
	config
	err      error
	builders []*NotificationTokenCreate
}

// Save creates the NotificationToken entities in the database.
func (_c *NotificationTokenCreateBulk) Save(ctx context.Context) ([]*NotificationToken, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*NotificationToken, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NotificationTokenMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *NotificationTokenCreateBulk) SaveX(ctx context.Context) []*NotificationToken {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NotificationTokenCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NotificationTokenCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
