// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"remi/server/ent/notificationtoken"
	"remi/server/ent/predicate"
	"remi/server/ent/user"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// NotificationTokenUpdate is the builder for updating NotificationToken entities.
type NotificationTokenUpdate struct {
	config
	hooks    []Hook
	mutation *NotificationTokenMutation
}

// Where appends a list predicates to the NotificationTokenUpdate builder.
func (_u *NotificationTokenUpdate) Where(ps ...predicate.NotificationToken) *NotificationTokenUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *NotificationTokenUpdate) SetUpdatedAt(v time.Time) *NotificationTokenUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetToken sets the "token" field.
func (_u *NotificationTokenUpdate) SetToken(v string) *NotificationTokenUpdate {
	_u.mutation.SetToken(v)
	return _u
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (_u *NotificationTokenUpdate) SetNillableToken(v *string) *NotificationTokenUpdate {
	if v != nil {
		_u.SetToken(*v)
	}
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *NotificationTokenUpdate) SetPlatform(v string) *NotificationTokenUpdate {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *NotificationTokenUpdate) SetNillablePlatform(v *string) *NotificationTokenUpdate {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetDeviceKey sets the "device_key" field.
func (_u *NotificationTokenUpdate) SetDeviceKey(v string) *NotificationTokenUpdate {
	_u.mutation.SetDeviceKey(v)
	return _u
}

// SetNillableDeviceKey sets the "device_key" field if the given value is not nil.
func (_u *NotificationTokenUpdate) SetNillableDeviceKey(v *string) *NotificationTokenUpdate {
	if v != nil {
		_u.SetDeviceKey(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *NotificationTokenUpdate) SetUserID(v int) *NotificationTokenUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *NotificationTokenUpdate) SetNillableUserID(v *int) *NotificationTokenUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *NotificationTokenUpdate) ClearUserID() *NotificationTokenUpdate {
	_u.mutation.ClearUserID()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *NotificationTokenUpdate) SetUser(v *User) *NotificationTokenUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the NotificationTokenMutation object of the builder.
func (_u *NotificationTokenUpdate) Mutation() *NotificationTokenMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *NotificationTokenUpdate) ClearUser() *NotificationTokenUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *NotificationTokenUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NotificationTokenUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *NotificationTokenUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NotificationTokenUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *NotificationTokenUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := notificationtoken.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NotificationTokenUpdate) check() error {
	if v, ok := _u.mutation.Token(); ok {
		if err := notificationtoken.TokenValidator(v); err != nil {
			return &ValidationError{Name: "token", err: fmt.Errorf(`ent: validator failed for field "NotificationToken.token": %w`, err)}
		}
	}
	return nil
}

func (_u *NotificationTokenUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(notificationtoken.Table, notificationtoken.Columns, sqlgraph.NewFieldSpec(notificationtoken.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(notificationtoken.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Token(); ok {
		_spec.SetField(notificationtoken.FieldToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(notificationtoken.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.DeviceKey(); ok {
		_spec.SetField(notificationtoken.FieldDeviceKey, field.TypeString, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notificationtoken.UserTable,
			Columns: []string{notificationtoken.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notificationtoken.UserTable,
			Columns: []string{notificationtoken.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notificationtoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// NotificationTokenUpdateOne is the builder for updating a single NotificationToken entity.
type NotificationTokenUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *NotificationTokenMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *NotificationTokenUpdateOne) SetUpdatedAt(v time.Time) *NotificationTokenUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetToken sets the "token" field.
func (_u *NotificationTokenUpdateOne) SetToken(v string) *NotificationTokenUpdateOne {
	_u.mutation.SetToken(v)
	return _u
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (_u *NotificationTokenUpdateOne) SetNillableToken(v *string) *NotificationTokenUpdateOne {
	if v != nil {
		_u.SetToken(*v)
	}
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *NotificationTokenUpdateOne) SetPlatform(v string) *NotificationTokenUpdateOne {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *NotificationTokenUpdateOne) SetNillablePlatform(v *string) *NotificationTokenUpdateOne {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetDeviceKey sets the "device_key" field.
func (_u *NotificationTokenUpdateOne) SetDeviceKey(v string) *NotificationTokenUpdateOne {
	_u.mutation.SetDeviceKey(v)
	return _u
}

// SetNillableDeviceKey sets the "device_key" field if the given value is not nil.
func (_u *NotificationTokenUpdateOne) SetNillableDeviceKey(v *string) *NotificationTokenUpdateOne {
	if v != nil {
		_u.SetDeviceKey(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *NotificationTokenUpdateOne) SetUserID(v int) *NotificationTokenUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *NotificationTokenUpdateOne) SetNillableUserID(v *int) *NotificationTokenUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *NotificationTokenUpdateOne) ClearUserID() *NotificationTokenUpdateOne {
	_u.mutation.ClearUserID()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *NotificationTokenUpdateOne) SetUser(v *User) *NotificationTokenUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the NotificationTokenMutation object of the builder.
func (_u *NotificationTokenUpdateOne) Mutation() *NotificationTokenMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *NotificationTokenUpdateOne) ClearUser() *NotificationTokenUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the NotificationTokenUpdate builder.
func (_u *NotificationTokenUpdateOne) Where(ps ...predicate.NotificationToken) *NotificationTokenUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *NotificationTokenUpdateOne) Select(field string, fields ...string) *NotificationTokenUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated NotificationToken entity.
func (_u *NotificationTokenUpdateOne) Save(ctx context.Context) (*NotificationToken, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NotificationTokenUpdateOne) SaveX(ctx context.Context) *NotificationToken {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *NotificationTokenUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NotificationTokenUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *NotificationTokenUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := notificationtoken.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NotificationTokenUpdateOne) check() error {
	if v, ok := _u.mutation.Token(); ok {
		if err := notificationtoken.TokenValidator(v); err != nil {
			return &ValidationError{Name: "token", err: fmt.Errorf(`ent: validator failed for field "NotificationToken.token": %w`, err)}
		}
	}
	return nil
}

func (_u *NotificationTokenUpdateOne) sqlSave(ctx context.Context) (_node *NotificationToken, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(notificationtoken.Table, notificationtoken.Columns, sqlgraph.NewFieldSpec(notificationtoken.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "NotificationToken.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, notificationtoken.FieldID)
		for _, f := range fields {
			if !notificationtoken.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != notificationtoken.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(notificationtoken.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Token(); ok {
		_spec.SetField(notificationtoken.FieldToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(notificationtoken.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.DeviceKey(); ok {
		_spec.SetField(notificationtoken.FieldDeviceKey, field.TypeString, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notificationtoken.UserTable,
			Columns: []string{notificationtoken.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notificationtoken.UserTable,
			Columns: []string{notificationtoken.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &NotificationToken{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notificationtoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
