// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"remi/server/ent/syncjob"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SyncJobCreate is the builder for creating a SyncJob entity.
type SyncJobCreate struct {
	config
	mutation *SyncJobMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *SyncJobCreate) SetCreatedAt(v time.Time) *SyncJobCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SyncJobCreate) SetNillableCreatedAt(v *time.Time) *SyncJobCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SyncJobCreate) SetUpdatedAt(v time.Time) *SyncJobCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SyncJobCreate) SetNillableUpdatedAt(v *time.Time) *SyncJobCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetJobID sets the "job_id" field.
func (_c *SyncJobCreate) SetJobID(v string) *SyncJobCreate {
	_c.mutation.SetJobID(v)
	return _c
}

// SetUID sets the "uid" field.
func (_c *SyncJobCreate) SetUID(v string) *SyncJobCreate {
	_c.mutation.SetUID(v)
	return _c
}

// SetConversationID sets the "conversation_id" field.
func (_c *SyncJobCreate) SetConversationID(v string) *SyncJobCreate {
	_c.mutation.SetConversationID(v)
	return _c
}

// SetNillableConversationID sets the "conversation_id" field if the given value is not nil.
func (_c *SyncJobCreate) SetNillableConversationID(v *string) *SyncJobCreate {
	if v != nil {
		_c.SetConversationID(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *SyncJobCreate) SetStatus(v string) *SyncJobCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *SyncJobCreate) SetNillableStatus(v *string) *SyncJobCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetTotalSegments sets the "total_segments" field.
func (_c *SyncJobCreate) SetTotalSegments(v int) *SyncJobCreate {
	_c.mutation.SetTotalSegments(v)
	return _c
}

// SetNillableTotalSegments sets the "total_segments" field if the given value is not nil.
func (_c *SyncJobCreate) SetNillableTotalSegments(v *int) *SyncJobCreate {
	if v != nil {
		_c.SetTotalSegments(*v)
	}
	return _c
}

// SetProcessedSegments sets the "processed_segments" field.
func (_c *SyncJobCreate) SetProcessedSegments(v int) *SyncJobCreate {
	_c.mutation.SetProcessedSegments(v)
	return _c
}

// SetNillableProcessedSegments sets the "processed_segments" field if the given value is not nil.
func (_c *SyncJobCreate) SetNillableProcessedSegments(v *int) *SyncJobCreate {
	if v != nil {
		_c.SetProcessedSegments(*v)
	}
	return _c
}

// SetSuccessfulSegments sets the "successful_segments" field.
func (_c *SyncJobCreate) SetSuccessfulSegments(v int) *SyncJobCreate {
	_c.mutation.SetSuccessfulSegments(v)
	return _c
}

// SetNillableSuccessfulSegments sets the "successful_segments" field if the given value is not nil.
func (_c *SyncJobCreate) SetNillableSuccessfulSegments(v *int) *SyncJobCreate {
	if v != nil {
		_c.SetSuccessfulSegments(*v)
	}
	return _c
}

// SetFailedSegments sets the "failed_segments" field.
func (_c *SyncJobCreate) SetFailedSegments(v int) *SyncJobCreate {
	_c.mutation.SetFailedSegments(v)
	return _c
}

// SetNillableFailedSegments sets the "failed_segments" field if the given value is not nil.
func (_c *SyncJobCreate) SetNillableFailedSegments(v *int) *SyncJobCreate {
	if v != nil {
		_c.SetFailedSegments(*v)
	}
	return _c
}

// SetLane sets the "lane" field.
func (_c *SyncJobCreate) SetLane(v string) *SyncJobCreate {
	_c.mutation.SetLane(v)
	return _c
}

// SetNillableLane sets the "lane" field if the given value is not nil.
func (_c *SyncJobCreate) SetNillableLane(v *string) *SyncJobCreate {
	if v != nil {
		_c.SetLane(*v)
	}
	return _c
}

// SetReasonCode sets the "reason_code" field.
func (_c *SyncJobCreate) SetReasonCode(v string) *SyncJobCreate {
	_c.mutation.SetReasonCode(v)
	return _c
}

// SetNillableReasonCode sets the "reason_code" field if the given value is not nil.
func (_c *SyncJobCreate) SetNillableReasonCode(v *string) *SyncJobCreate {
	if v != nil {
		_c.SetReasonCode(*v)
	}
	return _c
}

// SetRetryAfter sets the "retry_after" field.
func (_c *SyncJobCreate) SetRetryAfter(v int) *SyncJobCreate {
	_c.mutation.SetRetryAfter(v)
	return _c
}

// SetNillableRetryAfter sets the "retry_after" field if the given value is not nil.
func (_c *SyncJobCreate) SetNillableRetryAfter(v *int) *SyncJobCreate {
	if v != nil {
		_c.SetRetryAfter(*v)
	}
	return _c
}

// SetRecordingAgeSeconds sets the "recording_age_seconds" field.
func (_c *SyncJobCreate) SetRecordingAgeSeconds(v int) *SyncJobCreate {
	_c.mutation.SetRecordingAgeSeconds(v)
	return _c
}

// SetNillableRecordingAgeSeconds sets the "recording_age_seconds" field if the given value is not nil.
func (_c *SyncJobCreate) SetNillableRecordingAgeSeconds(v *int) *SyncJobCreate {
	if v != nil {
		_c.SetRecordingAgeSeconds(*v)
	}
	return _c
}

// SetError sets the "error" field.
func (_c *SyncJobCreate) SetError(v string) *SyncJobCreate {
	_c.mutation.SetError(v)
	return _c
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_c *SyncJobCreate) SetNillableError(v *string) *SyncJobCreate {
	if v != nil {
		_c.SetError(*v)
	}
	return _c
}

// SetResult sets the "result" field.
func (_c *SyncJobCreate) SetResult(v map[string]interface{}) *SyncJobCreate {
	_c.mutation.SetResult(v)
	return _c
}

// Mutation returns the SyncJobMutation object of the builder.
func (_c *SyncJobCreate) Mutation() *SyncJobMutation {
	return _c.mutation
}

// Save creates the SyncJob in the database.
func (_c *SyncJobCreate) Save(ctx context.Context) (*SyncJob, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SyncJobCreate) SaveX(ctx context.Context) *SyncJob {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SyncJobCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SyncJobCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SyncJobCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := syncjob.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := syncjob.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := syncjob.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.TotalSegments(); !ok {
		v := syncjob.DefaultTotalSegments
		_c.mutation.SetTotalSegments(v)
	}
	if _, ok := _c.mutation.ProcessedSegments(); !ok {
		v := syncjob.DefaultProcessedSegments
		_c.mutation.SetProcessedSegments(v)
	}
	if _, ok := _c.mutation.SuccessfulSegments(); !ok {
		v := syncjob.DefaultSuccessfulSegments
		_c.mutation.SetSuccessfulSegments(v)
	}
	if _, ok := _c.mutation.FailedSegments(); !ok {
		v := syncjob.DefaultFailedSegments
		_c.mutation.SetFailedSegments(v)
	}
	if _, ok := _c.mutation.Lane(); !ok {
		v := syncjob.DefaultLane
		_c.mutation.SetLane(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SyncJobCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SyncJob.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SyncJob.updated_at"`)}
	}
	if _, ok := _c.mutation.JobID(); !ok {
		return &ValidationError{Name: "job_id", err: errors.New(`ent: missing required field "SyncJob.job_id"`)}
	}
	if v, ok := _c.mutation.JobID(); ok {
		if err := syncjob.JobIDValidator(v); err != nil {
			return &ValidationError{Name: "job_id", err: fmt.Errorf(`ent: validator failed for field "SyncJob.job_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UID(); !ok {
		return &ValidationError{Name: "uid", err: errors.New(`ent: missing required field "SyncJob.uid"`)}
	}
	if v, ok := _c.mutation.UID(); ok {
		if err := syncjob.UIDValidator(v); err != nil {
			return &ValidationError{Name: "uid", err: fmt.Errorf(`ent: validator failed for field "SyncJob.uid": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "SyncJob.status"`)}
	}
	if _, ok := _c.mutation.TotalSegments(); !ok {
		return &ValidationError{Name: "total_segments", err: errors.New(`ent: missing required field "SyncJob.total_segments"`)}
	}
	if _, ok := _c.mutation.ProcessedSegments(); !ok {
		return &ValidationError{Name: "processed_segments", err: errors.New(`ent: missing required field "SyncJob.processed_segments"`)}
	}
	if _, ok := _c.mutation.SuccessfulSegments(); !ok {
		return &ValidationError{Name: "successful_segments", err: errors.New(`ent: missing required field "SyncJob.successful_segments"`)}
	}
	if _, ok := _c.mutation.FailedSegments(); !ok {
		return &ValidationError{Name: "failed_segments", err: errors.New(`ent: missing required field "SyncJob.failed_segments"`)}
	}
	if _, ok := _c.mutation.Lane(); !ok {
		return &ValidationError{Name: "lane", err: errors.New(`ent: missing required field "SyncJob.lane"`)}
	}
	return nil
}

func (_c *SyncJobCreate) sqlSave(ctx context.Context) (*SyncJob, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SyncJobCreate) createSpec() (*SyncJob, *sqlgraph.CreateSpec) {
	var (
		_node = &SyncJob{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(syncjob.Table, sqlgraph.NewFieldSpec(syncjob.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(syncjob.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(syncjob.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.JobID(); ok {
		_spec.SetField(syncjob.FieldJobID, field.TypeString, value)
		_node.JobID = value
	}
	if value, ok := _c.mutation.UID(); ok {
		_spec.SetField(syncjob.FieldUID, field.TypeString, value)
		_node.UID = value
	}
	if value, ok := _c.mutation.ConversationID(); ok {
		_spec.SetField(syncjob.FieldConversationID, field.TypeString, value)
		_node.ConversationID = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(syncjob.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.TotalSegments(); ok {
		_spec.SetField(syncjob.FieldTotalSegments, field.TypeInt, value)
		_node.TotalSegments = value
	}
	if value, ok := _c.mutation.ProcessedSegments(); ok {
		_spec.SetField(syncjob.FieldProcessedSegments, field.TypeInt, value)
		_node.ProcessedSegments = value
	}
	if value, ok := _c.mutation.SuccessfulSegments(); ok {
		_spec.SetField(syncjob.FieldSuccessfulSegments, field.TypeInt, value)
		_node.SuccessfulSegments = value
	}
	if value, ok := _c.mutation.FailedSegments(); ok {
		_spec.SetField(syncjob.FieldFailedSegments, field.TypeInt, value)
		_node.FailedSegments = value
	}
	if value, ok := _c.mutation.Lane(); ok {
		_spec.SetField(syncjob.FieldLane, field.TypeString, value)
		_node.Lane = value
	}
	if value, ok := _c.mutation.ReasonCode(); ok {
		_spec.SetField(syncjob.FieldReasonCode, field.TypeString, value)
		_node.ReasonCode = value
	}
	if value, ok := _c.mutation.RetryAfter(); ok {
		_spec.SetField(syncjob.FieldRetryAfter, field.TypeInt, value)
		_node.RetryAfter = value
	}
	if value, ok := _c.mutation.RecordingAgeSeconds(); ok {
		_spec.SetField(syncjob.FieldRecordingAgeSeconds, field.TypeInt, value)
		_node.RecordingAgeSeconds = value
	}
	if value, ok := _c.mutation.Error(); ok {
		_spec.SetField(syncjob.FieldError, field.TypeString, value)
		_node.Error = value
	}
	if value, ok := _c.mutation.Result(); ok {
		_spec.SetField(syncjob.FieldResult, field.TypeJSON, value)
		_node.Result = value
	}
	return _node, _spec
}

// SyncJobCreateBulk is the builder for creating many SyncJob entities in bulk.
type SyncJobCreateBulk struct {
	config
	err      error
	builders []*SyncJobCreate
}

// Save creates the SyncJob entities in the database.
func (_c *SyncJobCreateBulk) Save(ctx context.Context) ([]*SyncJob, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SyncJob, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SyncJobMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SyncJobCreateBulk) SaveX(ctx context.Context) []*SyncJob {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SyncJobCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SyncJobCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
