// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"remi/server/ent/conversation"
	"remi/server/ent/transcriptsegment"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// TranscriptSegment is the model entity for the TranscriptSegment schema.
type TranscriptSegment struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Speaker holds the value of the "speaker" field.
	Speaker string `json:"speaker,omitempty"`
	// SpeakerID holds the value of the "speaker_id" field.
	SpeakerID int `json:"speaker_id,omitempty"`
	// IsUser holds the value of the "is_user" field.
	IsUser bool `json:"is_user,omitempty"`
	// PersonID holds the value of the "person_id" field.
	PersonID *string `json:"person_id,omitempty"`
	// Text holds the value of the "text" field.
	Text string `json:"text,omitempty"`
	// StartMs holds the value of the "start_ms" field.
	StartMs int64 `json:"start_ms,omitempty"`
	// EndMs holds the value of the "end_ms" field.
	EndMs int64 `json:"end_ms,omitempty"`
	// Source holds the value of the "source" field.
	Source string `json:"source,omitempty"`
	// ConversationID holds the value of the "conversation_id" field.
	ConversationID *int `json:"conversation_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TranscriptSegmentQuery when eager-loading is set.
	Edges        TranscriptSegmentEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TranscriptSegmentEdges holds the relations/edges for other nodes in the graph.
type TranscriptSegmentEdges struct {
	// Conversation holds the value of the conversation edge.
	Conversation *Conversation `json:"conversation,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ConversationOrErr returns the Conversation value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TranscriptSegmentEdges) ConversationOrErr() (*Conversation, error) {
	if e.Conversation != nil {
		return e.Conversation, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: conversation.Label}
	}
	return nil, &NotLoadedError{edge: "conversation"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TranscriptSegment) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case transcriptsegment.FieldIsUser:
			values[i] = new(sql.NullBool)
		case transcriptsegment.FieldID, transcriptsegment.FieldSpeakerID, transcriptsegment.FieldStartMs, transcriptsegment.FieldEndMs, transcriptsegment.FieldConversationID:
			values[i] = new(sql.NullInt64)
		case transcriptsegment.FieldSpeaker, transcriptsegment.FieldPersonID, transcriptsegment.FieldText, transcriptsegment.FieldSource:
			values[i] = new(sql.NullString)
		case transcriptsegment.FieldCreatedAt, transcriptsegment.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TranscriptSegment fields.
func (_m *TranscriptSegment) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case transcriptsegment.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case transcriptsegment.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case transcriptsegment.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case transcriptsegment.FieldSpeaker:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field speaker", values[i])
			} else if value.Valid {
				_m.Speaker = value.String
			}
		case transcriptsegment.FieldSpeakerID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field speaker_id", values[i])
			} else if value.Valid {
				_m.SpeakerID = int(value.Int64)
			}
		case transcriptsegment.FieldIsUser:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_user", values[i])
			} else if value.Valid {
				_m.IsUser = value.Bool
			}
		case transcriptsegment.FieldPersonID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field person_id", values[i])
			} else if value.Valid {
				_m.PersonID = new(string)
				*_m.PersonID = value.String
			}
		case transcriptsegment.FieldText:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field text", values[i])
			} else if value.Valid {
				_m.Text = value.String
			}
		case transcriptsegment.FieldStartMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field start_ms", values[i])
			} else if value.Valid {
				_m.StartMs = value.Int64
			}
		case transcriptsegment.FieldEndMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field end_ms", values[i])
			} else if value.Valid {
				_m.EndMs = value.Int64
			}
		case transcriptsegment.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				_m.Source = value.String
			}
		case transcriptsegment.FieldConversationID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field conversation_id", values[i])
			} else if value.Valid {
				_m.ConversationID = new(int)
				*_m.ConversationID = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TranscriptSegment.
// This includes values selected through modifiers, order, etc.
func (_m *TranscriptSegment) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryConversation queries the "conversation" edge of the TranscriptSegment entity.
func (_m *TranscriptSegment) QueryConversation() *ConversationQuery {
	return NewTranscriptSegmentClient(_m.config).QueryConversation(_m)
}

// Update returns a builder for updating this TranscriptSegment.
// Note that you need to call TranscriptSegment.Unwrap() before calling this method if this TranscriptSegment
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *TranscriptSegment) Update() *TranscriptSegmentUpdateOne {
	return NewTranscriptSegmentClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the TranscriptSegment entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *TranscriptSegment) Unwrap() *TranscriptSegment {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: TranscriptSegment is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *TranscriptSegment) String() string {
	var builder strings.Builder
	builder.WriteString("TranscriptSegment(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("speaker=")
	builder.WriteString(_m.Speaker)
	builder.WriteString(", ")
	builder.WriteString("speaker_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SpeakerID))
	builder.WriteString(", ")
	builder.WriteString("is_user=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsUser))
	builder.WriteString(", ")
	if v := _m.PersonID; v != nil {
		builder.WriteString("person_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("text=")
	builder.WriteString(_m.Text)
	builder.WriteString(", ")
	builder.WriteString("start_ms=")
	builder.WriteString(fmt.Sprintf("%v", _m.StartMs))
	builder.WriteString(", ")
	builder.WriteString("end_ms=")
	builder.WriteString(fmt.Sprintf("%v", _m.EndMs))
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(_m.Source)
	builder.WriteString(", ")
	if v := _m.ConversationID; v != nil {
		builder.WriteString("conversation_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// TranscriptSegments is a parsable slice of TranscriptSegment.
type TranscriptSegments []*TranscriptSegment
