// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"remi/server/ent/actionitem"
	"remi/server/ent/calendarmeeting"
	"remi/server/ent/chatfile"
	"remi/server/ent/chatmessage"
	"remi/server/ent/chatsession"
	"remi/server/ent/conversation"
	"remi/server/ent/csatrating"
	"remi/server/ent/device"
	"remi/server/ent/folder"
	"remi/server/ent/goal"
	"remi/server/ent/memory"
	"remi/server/ent/notificationtoken"
	"remi/server/ent/todo"
	"remi/server/ent/user"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserCreate is the builder for creating a User entity.
type UserCreate struct {
	config
	mutation *UserMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserCreate) SetCreatedAt(v time.Time) *UserCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserCreate) SetNillableCreatedAt(v *time.Time) *UserCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UserCreate) SetUpdatedAt(v time.Time) *UserCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UserCreate) SetNillableUpdatedAt(v *time.Time) *UserCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetExternalUID sets the "external_uid" field.
func (_c *UserCreate) SetExternalUID(v string) *UserCreate {
	_c.mutation.SetExternalUID(v)
	return _c
}

// SetEmail sets the "email" field.
func (_c *UserCreate) SetEmail(v string) *UserCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetName sets the "name" field.
func (_c *UserCreate) SetName(v string) *UserCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_c *UserCreate) SetNillableName(v *string) *UserCreate {
	if v != nil {
		_c.SetName(*v)
	}
	return _c
}

// SetLanguage sets the "language" field.
func (_c *UserCreate) SetLanguage(v string) *UserCreate {
	_c.mutation.SetLanguage(v)
	return _c
}

// SetNillableLanguage sets the "language" field if the given value is not nil.
func (_c *UserCreate) SetNillableLanguage(v *string) *UserCreate {
	if v != nil {
		_c.SetLanguage(*v)
	}
	return _c
}

// SetTimeZone sets the "time_zone" field.
func (_c *UserCreate) SetTimeZone(v string) *UserCreate {
	_c.mutation.SetTimeZone(v)
	return _c
}

// SetNillableTimeZone sets the "time_zone" field if the given value is not nil.
func (_c *UserCreate) SetNillableTimeZone(v *string) *UserCreate {
	if v != nil {
		_c.SetTimeZone(*v)
	}
	return _c
}

// SetOnboarding sets the "onboarding" field.
func (_c *UserCreate) SetOnboarding(v map[string]interface{}) *UserCreate {
	_c.mutation.SetOnboarding(v)
	return _c
}

// SetPrivateCloudSyncEnabled sets the "private_cloud_sync_enabled" field.
func (_c *UserCreate) SetPrivateCloudSyncEnabled(v bool) *UserCreate {
	_c.mutation.SetPrivateCloudSyncEnabled(v)
	return _c
}

// SetNillablePrivateCloudSyncEnabled sets the "private_cloud_sync_enabled" field if the given value is not nil.
func (_c *UserCreate) SetNillablePrivateCloudSyncEnabled(v *bool) *UserCreate {
	if v != nil {
		_c.SetPrivateCloudSyncEnabled(*v)
	}
	return _c
}

// SetMeetingNoteScreenshotsEnabled sets the "meeting_note_screenshots_enabled" field.
func (_c *UserCreate) SetMeetingNoteScreenshotsEnabled(v bool) *UserCreate {
	_c.mutation.SetMeetingNoteScreenshotsEnabled(v)
	return _c
}

// SetNillableMeetingNoteScreenshotsEnabled sets the "meeting_note_screenshots_enabled" field if the given value is not nil.
func (_c *UserCreate) SetNillableMeetingNoteScreenshotsEnabled(v *bool) *UserCreate {
	if v != nil {
		_c.SetMeetingNoteScreenshotsEnabled(*v)
	}
	return _c
}

// SetStoreRecordingPermission sets the "store_recording_permission" field.
func (_c *UserCreate) SetStoreRecordingPermission(v bool) *UserCreate {
	_c.mutation.SetStoreRecordingPermission(v)
	return _c
}

// SetNillableStoreRecordingPermission sets the "store_recording_permission" field if the given value is not nil.
func (_c *UserCreate) SetNillableStoreRecordingPermission(v *bool) *UserCreate {
	if v != nil {
		_c.SetStoreRecordingPermission(*v)
	}
	return _c
}

// SetDailySummaryEnabled sets the "daily_summary_enabled" field.
func (_c *UserCreate) SetDailySummaryEnabled(v bool) *UserCreate {
	_c.mutation.SetDailySummaryEnabled(v)
	return _c
}

// SetNillableDailySummaryEnabled sets the "daily_summary_enabled" field if the given value is not nil.
func (_c *UserCreate) SetNillableDailySummaryEnabled(v *bool) *UserCreate {
	if v != nil {
		_c.SetDailySummaryEnabled(*v)
	}
	return _c
}

// SetDailySummaryHourLocal sets the "daily_summary_hour_local" field.
func (_c *UserCreate) SetDailySummaryHourLocal(v int) *UserCreate {
	_c.mutation.SetDailySummaryHourLocal(v)
	return _c
}

// SetNillableDailySummaryHourLocal sets the "daily_summary_hour_local" field if the given value is not nil.
func (_c *UserCreate) SetNillableDailySummaryHourLocal(v *int) *UserCreate {
	if v != nil {
		_c.SetDailySummaryHourLocal(*v)
	}
	return _c
}

// SetMentorNotificationFrequency sets the "mentor_notification_frequency" field.
func (_c *UserCreate) SetMentorNotificationFrequency(v int) *UserCreate {
	_c.mutation.SetMentorNotificationFrequency(v)
	return _c
}

// SetNillableMentorNotificationFrequency sets the "mentor_notification_frequency" field if the given value is not nil.
func (_c *UserCreate) SetNillableMentorNotificationFrequency(v *int) *UserCreate {
	if v != nil {
		_c.SetMentorNotificationFrequency(*v)
	}
	return _c
}

// SetIntegrations sets the "integrations" field.
func (_c *UserCreate) SetIntegrations(v map[string]interface{}) *UserCreate {
	_c.mutation.SetIntegrations(v)
	return _c
}

// SetNotificationSettings sets the "notification_settings" field.
func (_c *UserCreate) SetNotificationSettings(v map[string]interface{}) *UserCreate {
	_c.mutation.SetNotificationSettings(v)
	return _c
}

// SetAssistantSettings sets the "assistant_settings" field.
func (_c *UserCreate) SetAssistantSettings(v map[string]interface{}) *UserCreate {
	_c.mutation.SetAssistantSettings(v)
	return _c
}

// SetAiProfile sets the "ai_profile" field.
func (_c *UserCreate) SetAiProfile(v map[string]interface{}) *UserCreate {
	_c.mutation.SetAiProfile(v)
	return _c
}

// AddDeviceIDs adds the "devices" edge to the Device entity by IDs.
func (_c *UserCreate) AddDeviceIDs(ids ...int) *UserCreate {
	_c.mutation.AddDeviceIDs(ids...)
	return _c
}

// AddDevices adds the "devices" edges to the Device entity.
func (_c *UserCreate) AddDevices(v ...*Device) *UserCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddDeviceIDs(ids...)
}

// AddConversationIDs adds the "conversations" edge to the Conversation entity by IDs.
func (_c *UserCreate) AddConversationIDs(ids ...int) *UserCreate {
	_c.mutation.AddConversationIDs(ids...)
	return _c
}

// AddConversations adds the "conversations" edges to the Conversation entity.
func (_c *UserCreate) AddConversations(v ...*Conversation) *UserCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddConversationIDs(ids...)
}

// AddMemoryIDs adds the "memories" edge to the Memory entity by IDs.
func (_c *UserCreate) AddMemoryIDs(ids ...int) *UserCreate {
	_c.mutation.AddMemoryIDs(ids...)
	return _c
}

// AddMemories adds the "memories" edges to the Memory entity.
func (_c *UserCreate) AddMemories(v ...*Memory) *UserCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMemoryIDs(ids...)
}

// AddTodoIDs adds the "todos" edge to the Todo entity by IDs.
func (_c *UserCreate) AddTodoIDs(ids ...int) *UserCreate {
	_c.mutation.AddTodoIDs(ids...)
	return _c
}

// AddTodos adds the "todos" edges to the Todo entity.
func (_c *UserCreate) AddTodos(v ...*Todo) *UserCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTodoIDs(ids...)
}

// AddActionItemIDs adds the "action_items" edge to the ActionItem entity by IDs.
func (_c *UserCreate) AddActionItemIDs(ids ...int) *UserCreate {
	_c.mutation.AddActionItemIDs(ids...)
	return _c
}

// AddActionItems adds the "action_items" edges to the ActionItem entity.
func (_c *UserCreate) AddActionItems(v ...*ActionItem) *UserCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddActionItemIDs(ids...)
}

// AddChatMessageIDs adds the "chat_messages" edge to the ChatMessage entity by IDs.
func (_c *UserCreate) AddChatMessageIDs(ids ...int) *UserCreate {
	_c.mutation.AddChatMessageIDs(ids...)
	return _c
}

// AddChatMessages adds the "chat_messages" edges to the ChatMessage entity.
func (_c *UserCreate) AddChatMessages(v ...*ChatMessage) *UserCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddChatMessageIDs(ids...)
}

// AddChatSessionIDs adds the "chat_sessions" edge to the ChatSession entity by IDs.
func (_c *UserCreate) AddChatSessionIDs(ids ...int) *UserCreate {
	_c.mutation.AddChatSessionIDs(ids...)
	return _c
}

// AddChatSessions adds the "chat_sessions" edges to the ChatSession entity.
func (_c *UserCreate) AddChatSessions(v ...*ChatSession) *UserCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddChatSessionIDs(ids...)
}

// AddNotificationTokenIDs adds the "notification_tokens" edge to the NotificationToken entity by IDs.
func (_c *UserCreate) AddNotificationTokenIDs(ids ...int) *UserCreate {
	_c.mutation.AddNotificationTokenIDs(ids...)
	return _c
}

// AddNotificationTokens adds the "notification_tokens" edges to the NotificationToken entity.
func (_c *UserCreate) AddNotificationTokens(v ...*NotificationToken) *UserCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddNotificationTokenIDs(ids...)
}

// AddFolderIDs adds the "folders" edge to the Folder entity by IDs.
func (_c *UserCreate) AddFolderIDs(ids ...int) *UserCreate {
	_c.mutation.AddFolderIDs(ids...)
	return _c
}

// AddFolders adds the "folders" edges to the Folder entity.
func (_c *UserCreate) AddFolders(v ...*Folder) *UserCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddFolderIDs(ids...)
}

// AddGoalIDs adds the "goals" edge to the Goal entity by IDs.
func (_c *UserCreate) AddGoalIDs(ids ...int) *UserCreate {
	_c.mutation.AddGoalIDs(ids...)
	return _c
}

// AddGoals adds the "goals" edges to the Goal entity.
func (_c *UserCreate) AddGoals(v ...*Goal) *UserCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddGoalIDs(ids...)
}

// AddCalendarMeetingIDs adds the "calendar_meetings" edge to the CalendarMeeting entity by IDs.
func (_c *UserCreate) AddCalendarMeetingIDs(ids ...int) *UserCreate {
	_c.mutation.AddCalendarMeetingIDs(ids...)
	return _c
}

// AddCalendarMeetings adds the "calendar_meetings" edges to the CalendarMeeting entity.
func (_c *UserCreate) AddCalendarMeetings(v ...*CalendarMeeting) *UserCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddCalendarMeetingIDs(ids...)
}

// AddCsatRatingIDs adds the "csat_ratings" edge to the CsatRating entity by IDs.
func (_c *UserCreate) AddCsatRatingIDs(ids ...int) *UserCreate {
	_c.mutation.AddCsatRatingIDs(ids...)
	return _c
}

// AddCsatRatings adds the "csat_ratings" edges to the CsatRating entity.
func (_c *UserCreate) AddCsatRatings(v ...*CsatRating) *UserCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddCsatRatingIDs(ids...)
}

// AddChatFileIDs adds the "chat_files" edge to the ChatFile entity by IDs.
func (_c *UserCreate) AddChatFileIDs(ids ...int) *UserCreate {
	_c.mutation.AddChatFileIDs(ids...)
	return _c
}

// AddChatFiles adds the "chat_files" edges to the ChatFile entity.
func (_c *UserCreate) AddChatFiles(v ...*ChatFile) *UserCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddChatFileIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (_c *UserCreate) Mutation() *UserMutation {
	return _c.mutation
}

// Save creates the User in the database.
func (_c *UserCreate) Save(ctx context.Context) (*User, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserCreate) SaveX(ctx context.Context) *User {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := user.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := user.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Name(); !ok {
		v := user.DefaultName
		_c.mutation.SetName(v)
	}
	if _, ok := _c.mutation.Language(); !ok {
		v := user.DefaultLanguage
		_c.mutation.SetLanguage(v)
	}
	if _, ok := _c.mutation.TimeZone(); !ok {
		v := user.DefaultTimeZone
		_c.mutation.SetTimeZone(v)
	}
	if _, ok := _c.mutation.PrivateCloudSyncEnabled(); !ok {
		v := user.DefaultPrivateCloudSyncEnabled
		_c.mutation.SetPrivateCloudSyncEnabled(v)
	}
	if _, ok := _c.mutation.MeetingNoteScreenshotsEnabled(); !ok {
		v := user.DefaultMeetingNoteScreenshotsEnabled
		_c.mutation.SetMeetingNoteScreenshotsEnabled(v)
	}
	if _, ok := _c.mutation.StoreRecordingPermission(); !ok {
		v := user.DefaultStoreRecordingPermission
		_c.mutation.SetStoreRecordingPermission(v)
	}
	if _, ok := _c.mutation.DailySummaryEnabled(); !ok {
		v := user.DefaultDailySummaryEnabled
		_c.mutation.SetDailySummaryEnabled(v)
	}
	if _, ok := _c.mutation.DailySummaryHourLocal(); !ok {
		v := user.DefaultDailySummaryHourLocal
		_c.mutation.SetDailySummaryHourLocal(v)
	}
	if _, ok := _c.mutation.MentorNotificationFrequency(); !ok {
		v := user.DefaultMentorNotificationFrequency
		_c.mutation.SetMentorNotificationFrequency(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "User.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "User.updated_at"`)}
	}
	if _, ok := _c.mutation.ExternalUID(); !ok {
		return &ValidationError{Name: "external_uid", err: errors.New(`ent: missing required field "User.external_uid"`)}
	}
	if v, ok := _c.mutation.ExternalUID(); ok {
		if err := user.ExternalUIDValidator(v); err != nil {
			return &ValidationError{Name: "external_uid", err: fmt.Errorf(`ent: validator failed for field "User.external_uid": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "User.email"`)}
	}
	if v, ok := _c.mutation.Email(); ok {
		if err := user.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "User.email": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "User.name"`)}
	}
	if _, ok := _c.mutation.Language(); !ok {
		return &ValidationError{Name: "language", err: errors.New(`ent: missing required field "User.language"`)}
	}
	if _, ok := _c.mutation.TimeZone(); !ok {
		return &ValidationError{Name: "time_zone", err: errors.New(`ent: missing required field "User.time_zone"`)}
	}
	if _, ok := _c.mutation.PrivateCloudSyncEnabled(); !ok {
		return &ValidationError{Name: "private_cloud_sync_enabled", err: errors.New(`ent: missing required field "User.private_cloud_sync_enabled"`)}
	}
	if _, ok := _c.mutation.MeetingNoteScreenshotsEnabled(); !ok {
		return &ValidationError{Name: "meeting_note_screenshots_enabled", err: errors.New(`ent: missing required field "User.meeting_note_screenshots_enabled"`)}
	}
	if _, ok := _c.mutation.StoreRecordingPermission(); !ok {
		return &ValidationError{Name: "store_recording_permission", err: errors.New(`ent: missing required field "User.store_recording_permission"`)}
	}
	if _, ok := _c.mutation.DailySummaryEnabled(); !ok {
		return &ValidationError{Name: "daily_summary_enabled", err: errors.New(`ent: missing required field "User.daily_summary_enabled"`)}
	}
	if _, ok := _c.mutation.DailySummaryHourLocal(); !ok {
		return &ValidationError{Name: "daily_summary_hour_local", err: errors.New(`ent: missing required field "User.daily_summary_hour_local"`)}
	}
	if _, ok := _c.mutation.MentorNotificationFrequency(); !ok {
		return &ValidationError{Name: "mentor_notification_frequency", err: errors.New(`ent: missing required field "User.mentor_notification_frequency"`)}
	}
	return nil
}

func (_c *UserCreate) sqlSave(ctx context.Context) (*User, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserCreate) createSpec() (*User, *sqlgraph.CreateSpec) {
	var (
		_node = &User{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(user.Table, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(user.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(user.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.ExternalUID(); ok {
		_spec.SetField(user.FieldExternalUID, field.TypeString, value)
		_node.ExternalUID = value
	}
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(user.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Language(); ok {
		_spec.SetField(user.FieldLanguage, field.TypeString, value)
		_node.Language = value
	}
	if value, ok := _c.mutation.TimeZone(); ok {
		_spec.SetField(user.FieldTimeZone, field.TypeString, value)
		_node.TimeZone = value
	}
	if value, ok := _c.mutation.Onboarding(); ok {
		_spec.SetField(user.FieldOnboarding, field.TypeJSON, value)
		_node.Onboarding = value
	}
	if value, ok := _c.mutation.PrivateCloudSyncEnabled(); ok {
		_spec.SetField(user.FieldPrivateCloudSyncEnabled, field.TypeBool, value)
		_node.PrivateCloudSyncEnabled = value
	}
	if value, ok := _c.mutation.MeetingNoteScreenshotsEnabled(); ok {
		_spec.SetField(user.FieldMeetingNoteScreenshotsEnabled, field.TypeBool, value)
		_node.MeetingNoteScreenshotsEnabled = value
	}
	if value, ok := _c.mutation.StoreRecordingPermission(); ok {
		_spec.SetField(user.FieldStoreRecordingPermission, field.TypeBool, value)
		_node.StoreRecordingPermission = value
	}
	if value, ok := _c.mutation.DailySummaryEnabled(); ok {
		_spec.SetField(user.FieldDailySummaryEnabled, field.TypeBool, value)
		_node.DailySummaryEnabled = value
	}
	if value, ok := _c.mutation.DailySummaryHourLocal(); ok {
		_spec.SetField(user.FieldDailySummaryHourLocal, field.TypeInt, value)
		_node.DailySummaryHourLocal = value
	}
	if value, ok := _c.mutation.MentorNotificationFrequency(); ok {
		_spec.SetField(user.FieldMentorNotificationFrequency, field.TypeInt, value)
		_node.MentorNotificationFrequency = value
	}
	if value, ok := _c.mutation.Integrations(); ok {
		_spec.SetField(user.FieldIntegrations, field.TypeJSON, value)
		_node.Integrations = value
	}
	if value, ok := _c.mutation.NotificationSettings(); ok {
		_spec.SetField(user.FieldNotificationSettings, field.TypeJSON, value)
		_node.NotificationSettings = value
	}
	if value, ok := _c.mutation.AssistantSettings(); ok {
		_spec.SetField(user.FieldAssistantSettings, field.TypeJSON, value)
		_node.AssistantSettings = value
	}
	if value, ok := _c.mutation.AiProfile(); ok {
		_spec.SetField(user.FieldAiProfile, field.TypeJSON, value)
		_node.AiProfile = value
	}
	if nodes := _c.mutation.DevicesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.DevicesTable,
			Columns: []string{user.DevicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(device.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ConversationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ConversationsTable,
			Columns: []string{user.ConversationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.MemoriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.MemoriesTable,
			Columns: []string{user.MemoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(memory.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TodosIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.TodosTable,
			Columns: []string{user.TodosColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(todo.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ActionItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ActionItemsTable,
			Columns: []string{user.ActionItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(actionitem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ChatMessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ChatMessagesTable,
			Columns: []string{user.ChatMessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatmessage.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ChatSessionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ChatSessionsTable,
			Columns: []string{user.ChatSessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatsession.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.NotificationTokensIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.NotificationTokensTable,
			Columns: []string{user.NotificationTokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationtoken.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.FoldersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.FoldersTable,
			Columns: []string{user.FoldersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(folder.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.GoalsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.GoalsTable,
			Columns: []string{user.GoalsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(goal.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CalendarMeetingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.CalendarMeetingsTable,
			Columns: []string{user.CalendarMeetingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(calendarmeeting.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CsatRatingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.CsatRatingsTable,
			Columns: []string{user.CsatRatingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(csatrating.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ChatFilesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ChatFilesTable,
			Columns: []string{user.ChatFilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatfile.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// UserCreateBulk is the builder for creating many User entities in bulk.
type UserCreateBulk struct {
	config
	err      error
	builders []*UserCreate
}

// Save creates the User entities in the database.
func (_c *UserCreateBulk) Save(ctx context.Context) ([]*User, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*User, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserCreateBulk) SaveX(ctx context.Context) []*User {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
