// Code generated by ent, DO NOT EDIT.

package transcriptsegment

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the transcriptsegment type in the database.
	Label = "transcript_segment"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldSpeaker holds the string denoting the speaker field in the database.
	FieldSpeaker = "speaker"
	// FieldSpeakerID holds the string denoting the speaker_id field in the database.
	FieldSpeakerID = "speaker_id"
	// FieldIsUser holds the string denoting the is_user field in the database.
	FieldIsUser = "is_user"
	// FieldPersonID holds the string denoting the person_id field in the database.
	FieldPersonID = "person_id"
	// FieldText holds the string denoting the text field in the database.
	FieldText = "text"
	// FieldStartMs holds the string denoting the start_ms field in the database.
	FieldStartMs = "start_ms"
	// FieldEndMs holds the string denoting the end_ms field in the database.
	FieldEndMs = "end_ms"
	// FieldSource holds the string denoting the source field in the database.
	FieldSource = "source"
	// FieldConversationID holds the string denoting the conversation_id field in the database.
	FieldConversationID = "conversation_id"
	// EdgeConversation holds the string denoting the conversation edge name in mutations.
	EdgeConversation = "conversation"
	// Table holds the table name of the transcriptsegment in the database.
	Table = "transcript_segments"
	// ConversationTable is the table that holds the conversation relation/edge.
	ConversationTable = "transcript_segments"
	// ConversationInverseTable is the table name for the Conversation entity.
	// It exists in this package in order to avoid circular dependency with the "conversation" package.
	ConversationInverseTable = "conversations"
	// ConversationColumn is the table column denoting the conversation relation/edge.
	ConversationColumn = "conversation_id"
)

// Columns holds all SQL columns for transcriptsegment fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldSpeaker,
	FieldSpeakerID,
	FieldIsUser,
	FieldPersonID,
	FieldText,
	FieldStartMs,
	FieldEndMs,
	FieldSource,
	FieldConversationID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultSpeaker holds the default value on creation for the "speaker" field.
	DefaultSpeaker string
	// DefaultSpeakerID holds the default value on creation for the "speaker_id" field.
	DefaultSpeakerID int
	// DefaultIsUser holds the default value on creation for the "is_user" field.
	DefaultIsUser bool
	// StartMsValidator is a validator for the "start_ms" field. It is called by the builders before save.
	StartMsValidator func(int64) error
	// EndMsValidator is a validator for the "end_ms" field. It is called by the builders before save.
	EndMsValidator func(int64) error
	// DefaultSource holds the default value on creation for the "source" field.
	DefaultSource string
)

// OrderOption defines the ordering options for the TranscriptSegment queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// BySpeaker orders the results by the speaker field.
func BySpeaker(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSpeaker, opts...).ToFunc()
}

// BySpeakerID orders the results by the speaker_id field.
func BySpeakerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSpeakerID, opts...).ToFunc()
}

// ByIsUser orders the results by the is_user field.
func ByIsUser(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsUser, opts...).ToFunc()
}

// ByPersonID orders the results by the person_id field.
func ByPersonID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPersonID, opts...).ToFunc()
}

// ByText orders the results by the text field.
func ByText(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldText, opts...).ToFunc()
}

// ByStartMs orders the results by the start_ms field.
func ByStartMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartMs, opts...).ToFunc()
}

// ByEndMs orders the results by the end_ms field.
func ByEndMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEndMs, opts...).ToFunc()
}

// BySource orders the results by the source field.
func BySource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSource, opts...).ToFunc()
}

// ByConversationID orders the results by the conversation_id field.
func ByConversationID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConversationID, opts...).ToFunc()
}

// ByConversationField orders the results by conversation field.
func ByConversationField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newConversationStep(), sql.OrderByField(field, opts...))
	}
}
func newConversationStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ConversationInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ConversationTable, ConversationColumn),
	)
}
