// Code generated by ent, DO NOT EDIT.

package actionitem

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the actionitem type in the database.
	Label = "action_item"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldOwner holds the string denoting the owner field in the database.
	FieldOwner = "owner"
	// FieldPriority holds the string denoting the priority field in the database.
	FieldPriority = "priority"
	// FieldDueConfidence holds the string denoting the due_confidence field in the database.
	FieldDueConfidence = "due_confidence"
	// FieldSource holds the string denoting the source field in the database.
	FieldSource = "source"
	// FieldProvenance holds the string denoting the provenance field in the database.
	FieldProvenance = "provenance"
	// FieldSortOrder holds the string denoting the sort_order field in the database.
	FieldSortOrder = "sort_order"
	// FieldIndentLevel holds the string denoting the indent_level field in the database.
	FieldIndentLevel = "indent_level"
	// FieldRecurrenceRule holds the string denoting the recurrence_rule field in the database.
	FieldRecurrenceRule = "recurrence_rule"
	// FieldRecurrenceParentID holds the string denoting the recurrence_parent_id field in the database.
	FieldRecurrenceParentID = "recurrence_parent_id"
	// FieldDueAt holds the string denoting the due_at field in the database.
	FieldDueAt = "due_at"
	// FieldCompletedAt holds the string denoting the completed_at field in the database.
	FieldCompletedAt = "completed_at"
	// FieldSupersededBy holds the string denoting the superseded_by field in the database.
	FieldSupersededBy = "superseded_by"
	// FieldIsLocked holds the string denoting the is_locked field in the database.
	FieldIsLocked = "is_locked"
	// FieldExported holds the string denoting the exported field in the database.
	FieldExported = "exported"
	// FieldExportDate holds the string denoting the export_date field in the database.
	FieldExportDate = "export_date"
	// FieldExportPlatform holds the string denoting the export_platform field in the database.
	FieldExportPlatform = "export_platform"
	// FieldAppleReminderID holds the string denoting the apple_reminder_id field in the database.
	FieldAppleReminderID = "apple_reminder_id"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeConversation holds the string denoting the conversation edge name in mutations.
	EdgeConversation = "conversation"
	// Table holds the table name of the actionitem in the database.
	Table = "action_items"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "action_items"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_action_items"
	// ConversationTable is the table that holds the conversation relation/edge.
	ConversationTable = "action_items"
	// ConversationInverseTable is the table name for the Conversation entity.
	// It exists in this package in order to avoid circular dependency with the "conversation" package.
	ConversationInverseTable = "conversations"
	// ConversationColumn is the table column denoting the conversation relation/edge.
	ConversationColumn = "conversation_action_items"
)

// Columns holds all SQL columns for actionitem fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDescription,
	FieldStatus,
	FieldOwner,
	FieldPriority,
	FieldDueConfidence,
	FieldSource,
	FieldProvenance,
	FieldSortOrder,
	FieldIndentLevel,
	FieldRecurrenceRule,
	FieldRecurrenceParentID,
	FieldDueAt,
	FieldCompletedAt,
	FieldSupersededBy,
	FieldIsLocked,
	FieldExported,
	FieldExportDate,
	FieldExportPlatform,
	FieldAppleReminderID,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "action_items"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"conversation_action_items",
	"user_action_items",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	DescriptionValidator func(string) error
	// DefaultSource holds the default value on creation for the "source" field.
	DefaultSource string
	// DefaultSortOrder holds the default value on creation for the "sort_order" field.
	DefaultSortOrder int
	// DefaultIndentLevel holds the default value on creation for the "indent_level" field.
	DefaultIndentLevel int
	// IndentLevelValidator is a validator for the "indent_level" field. It is called by the builders before save.
	IndentLevelValidator func(int) error
	// DefaultIsLocked holds the default value on creation for the "is_locked" field.
	DefaultIsLocked bool
	// DefaultExported holds the default value on creation for the "exported" field.
	DefaultExported bool
)

// Status defines the type for the "status" enum field.
type Status string

// StatusActive is the default value of the Status enum.
const DefaultStatus = StatusActive

// Status values.
const (
	StatusActive     Status = "active"
	StatusCompleted  Status = "completed"
	StatusCancelled  Status = "cancelled"
	StatusSuperseded Status = "superseded"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusActive, StatusCompleted, StatusCancelled, StatusSuperseded:
		return nil
	default:
		return fmt.Errorf("actionitem: invalid enum value for status field: %q", s)
	}
}

// Owner defines the type for the "owner" enum field.
type Owner string

// OwnerUser is the default value of the Owner enum.
const DefaultOwner = OwnerUser

// Owner values.
const (
	OwnerUser    Owner = "user"
	OwnerOther   Owner = "other"
	OwnerUnknown Owner = "unknown"
)

func (o Owner) String() string {
	return string(o)
}

// OwnerValidator is a validator for the "owner" field enum values. It is called by the builders before save.
func OwnerValidator(o Owner) error {
	switch o {
	case OwnerUser, OwnerOther, OwnerUnknown:
		return nil
	default:
		return fmt.Errorf("actionitem: invalid enum value for owner field: %q", o)
	}
}

// Priority defines the type for the "priority" enum field.
type Priority string

// Priority values.
const (
	PriorityHigh   Priority = "high"
	PriorityMedium Priority = "medium"
	PriorityLow    Priority = "low"
)

func (pr Priority) String() string {
	return string(pr)
}

// PriorityValidator is a validator for the "priority" field enum values. It is called by the builders before save.
func PriorityValidator(pr Priority) error {
	switch pr {
	case PriorityHigh, PriorityMedium, PriorityLow:
		return nil
	default:
		return fmt.Errorf("actionitem: invalid enum value for priority field: %q", pr)
	}
}

// OrderOption defines the ordering options for the ActionItem queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByOwner orders the results by the owner field.
func ByOwner(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOwner, opts...).ToFunc()
}

// ByPriority orders the results by the priority field.
func ByPriority(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPriority, opts...).ToFunc()
}

// ByDueConfidence orders the results by the due_confidence field.
func ByDueConfidence(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDueConfidence, opts...).ToFunc()
}

// BySource orders the results by the source field.
func BySource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSource, opts...).ToFunc()
}

// BySortOrder orders the results by the sort_order field.
func BySortOrder(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSortOrder, opts...).ToFunc()
}

// ByIndentLevel orders the results by the indent_level field.
func ByIndentLevel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIndentLevel, opts...).ToFunc()
}

// ByRecurrenceRule orders the results by the recurrence_rule field.
func ByRecurrenceRule(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRecurrenceRule, opts...).ToFunc()
}

// ByRecurrenceParentID orders the results by the recurrence_parent_id field.
func ByRecurrenceParentID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRecurrenceParentID, opts...).ToFunc()
}

// ByDueAt orders the results by the due_at field.
func ByDueAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDueAt, opts...).ToFunc()
}

// ByCompletedAt orders the results by the completed_at field.
func ByCompletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompletedAt, opts...).ToFunc()
}

// BySupersededBy orders the results by the superseded_by field.
func BySupersededBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSupersededBy, opts...).ToFunc()
}

// ByIsLocked orders the results by the is_locked field.
func ByIsLocked(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsLocked, opts...).ToFunc()
}

// ByExported orders the results by the exported field.
func ByExported(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExported, opts...).ToFunc()
}

// ByExportDate orders the results by the export_date field.
func ByExportDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExportDate, opts...).ToFunc()
}

// ByExportPlatform orders the results by the export_platform field.
func ByExportPlatform(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExportPlatform, opts...).ToFunc()
}

// ByAppleReminderID orders the results by the apple_reminder_id field.
func ByAppleReminderID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAppleReminderID, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByConversationField orders the results by conversation field.
func ByConversationField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newConversationStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
func newConversationStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ConversationInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ConversationTable, ConversationColumn),
	)
}
