// Code generated by ent, DO NOT EDIT.

package syncjob

import (
	"remi/server/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldEQ(FieldUpdatedAt, v))
}

// JobID applies equality check predicate on the "job_id" field. It's identical to JobIDEQ.
func JobID(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldEQ(FieldJobID, v))
}

// UID applies equality check predicate on the "uid" field. It's identical to UIDEQ.
func UID(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldEQ(FieldUID, v))
}

// ConversationID applies equality check predicate on the "conversation_id" field. It's identical to ConversationIDEQ.
func ConversationID(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldEQ(FieldConversationID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldEQ(FieldStatus, v))
}

// TotalSegments applies equality check predicate on the "total_segments" field. It's identical to TotalSegmentsEQ.
func TotalSegments(v int) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldEQ(FieldTotalSegments, v))
}

// ProcessedSegments applies equality check predicate on the "processed_segments" field. It's identical to ProcessedSegmentsEQ.
func ProcessedSegments(v int) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldEQ(FieldProcessedSegments, v))
}

// SuccessfulSegments applies equality check predicate on the "successful_segments" field. It's identical to SuccessfulSegmentsEQ.
func SuccessfulSegments(v int) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldEQ(FieldSuccessfulSegments, v))
}

// FailedSegments applies equality check predicate on the "failed_segments" field. It's identical to FailedSegmentsEQ.
func FailedSegments(v int) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldEQ(FieldFailedSegments, v))
}

// Lane applies equality check predicate on the "lane" field. It's identical to LaneEQ.
func Lane(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldEQ(FieldLane, v))
}

// ReasonCode applies equality check predicate on the "reason_code" field. It's identical to ReasonCodeEQ.
func ReasonCode(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldEQ(FieldReasonCode, v))
}

// RetryAfter applies equality check predicate on the "retry_after" field. It's identical to RetryAfterEQ.
func RetryAfter(v int) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldEQ(FieldRetryAfter, v))
}

// RecordingAgeSeconds applies equality check predicate on the "recording_age_seconds" field. It's identical to RecordingAgeSecondsEQ.
func RecordingAgeSeconds(v int) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldEQ(FieldRecordingAgeSeconds, v))
}

// Error applies equality check predicate on the "error" field. It's identical to ErrorEQ.
func Error(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldEQ(FieldError, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldLTE(FieldUpdatedAt, v))
}

// JobIDEQ applies the EQ predicate on the "job_id" field.
func JobIDEQ(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldEQ(FieldJobID, v))
}

// JobIDNEQ applies the NEQ predicate on the "job_id" field.
func JobIDNEQ(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldNEQ(FieldJobID, v))
}

// JobIDIn applies the In predicate on the "job_id" field.
func JobIDIn(vs ...string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldIn(FieldJobID, vs...))
}

// JobIDNotIn applies the NotIn predicate on the "job_id" field.
func JobIDNotIn(vs ...string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldNotIn(FieldJobID, vs...))
}

// JobIDGT applies the GT predicate on the "job_id" field.
func JobIDGT(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldGT(FieldJobID, v))
}

// JobIDGTE applies the GTE predicate on the "job_id" field.
func JobIDGTE(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldGTE(FieldJobID, v))
}

// JobIDLT applies the LT predicate on the "job_id" field.
func JobIDLT(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldLT(FieldJobID, v))
}

// JobIDLTE applies the LTE predicate on the "job_id" field.
func JobIDLTE(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldLTE(FieldJobID, v))
}

// JobIDContains applies the Contains predicate on the "job_id" field.
func JobIDContains(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldContains(FieldJobID, v))
}

// JobIDHasPrefix applies the HasPrefix predicate on the "job_id" field.
func JobIDHasPrefix(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldHasPrefix(FieldJobID, v))
}

// JobIDHasSuffix applies the HasSuffix predicate on the "job_id" field.
func JobIDHasSuffix(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldHasSuffix(FieldJobID, v))
}

// JobIDEqualFold applies the EqualFold predicate on the "job_id" field.
func JobIDEqualFold(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldEqualFold(FieldJobID, v))
}

// JobIDContainsFold applies the ContainsFold predicate on the "job_id" field.
func JobIDContainsFold(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldContainsFold(FieldJobID, v))
}

// UIDEQ applies the EQ predicate on the "uid" field.
func UIDEQ(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldEQ(FieldUID, v))
}

// UIDNEQ applies the NEQ predicate on the "uid" field.
func UIDNEQ(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldNEQ(FieldUID, v))
}

// UIDIn applies the In predicate on the "uid" field.
func UIDIn(vs ...string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldIn(FieldUID, vs...))
}

// UIDNotIn applies the NotIn predicate on the "uid" field.
func UIDNotIn(vs ...string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldNotIn(FieldUID, vs...))
}

// UIDGT applies the GT predicate on the "uid" field.
func UIDGT(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldGT(FieldUID, v))
}

// UIDGTE applies the GTE predicate on the "uid" field.
func UIDGTE(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldGTE(FieldUID, v))
}

// UIDLT applies the LT predicate on the "uid" field.
func UIDLT(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldLT(FieldUID, v))
}

// UIDLTE applies the LTE predicate on the "uid" field.
func UIDLTE(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldLTE(FieldUID, v))
}

// UIDContains applies the Contains predicate on the "uid" field.
func UIDContains(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldContains(FieldUID, v))
}

// UIDHasPrefix applies the HasPrefix predicate on the "uid" field.
func UIDHasPrefix(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldHasPrefix(FieldUID, v))
}

// UIDHasSuffix applies the HasSuffix predicate on the "uid" field.
func UIDHasSuffix(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldHasSuffix(FieldUID, v))
}

// UIDEqualFold applies the EqualFold predicate on the "uid" field.
func UIDEqualFold(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldEqualFold(FieldUID, v))
}

// UIDContainsFold applies the ContainsFold predicate on the "uid" field.
func UIDContainsFold(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldContainsFold(FieldUID, v))
}

// ConversationIDEQ applies the EQ predicate on the "conversation_id" field.
func ConversationIDEQ(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldEQ(FieldConversationID, v))
}

// ConversationIDNEQ applies the NEQ predicate on the "conversation_id" field.
func ConversationIDNEQ(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldNEQ(FieldConversationID, v))
}

// ConversationIDIn applies the In predicate on the "conversation_id" field.
func ConversationIDIn(vs ...string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldIn(FieldConversationID, vs...))
}

// ConversationIDNotIn applies the NotIn predicate on the "conversation_id" field.
func ConversationIDNotIn(vs ...string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldNotIn(FieldConversationID, vs...))
}

// ConversationIDGT applies the GT predicate on the "conversation_id" field.
func ConversationIDGT(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldGT(FieldConversationID, v))
}

// ConversationIDGTE applies the GTE predicate on the "conversation_id" field.
func ConversationIDGTE(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldGTE(FieldConversationID, v))
}

// ConversationIDLT applies the LT predicate on the "conversation_id" field.
func ConversationIDLT(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldLT(FieldConversationID, v))
}

// ConversationIDLTE applies the LTE predicate on the "conversation_id" field.
func ConversationIDLTE(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldLTE(FieldConversationID, v))
}

// ConversationIDContains applies the Contains predicate on the "conversation_id" field.
func ConversationIDContains(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldContains(FieldConversationID, v))
}

// ConversationIDHasPrefix applies the HasPrefix predicate on the "conversation_id" field.
func ConversationIDHasPrefix(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldHasPrefix(FieldConversationID, v))
}

// ConversationIDHasSuffix applies the HasSuffix predicate on the "conversation_id" field.
func ConversationIDHasSuffix(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldHasSuffix(FieldConversationID, v))
}

// ConversationIDIsNil applies the IsNil predicate on the "conversation_id" field.
func ConversationIDIsNil() predicate.SyncJob {
	return predicate.SyncJob(sql.FieldIsNull(FieldConversationID))
}

// ConversationIDNotNil applies the NotNil predicate on the "conversation_id" field.
func ConversationIDNotNil() predicate.SyncJob {
	return predicate.SyncJob(sql.FieldNotNull(FieldConversationID))
}

// ConversationIDEqualFold applies the EqualFold predicate on the "conversation_id" field.
func ConversationIDEqualFold(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldEqualFold(FieldConversationID, v))
}

// ConversationIDContainsFold applies the ContainsFold predicate on the "conversation_id" field.
func ConversationIDContainsFold(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldContainsFold(FieldConversationID, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldContainsFold(FieldStatus, v))
}

// TotalSegmentsEQ applies the EQ predicate on the "total_segments" field.
func TotalSegmentsEQ(v int) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldEQ(FieldTotalSegments, v))
}

// TotalSegmentsNEQ applies the NEQ predicate on the "total_segments" field.
func TotalSegmentsNEQ(v int) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldNEQ(FieldTotalSegments, v))
}

// TotalSegmentsIn applies the In predicate on the "total_segments" field.
func TotalSegmentsIn(vs ...int) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldIn(FieldTotalSegments, vs...))
}

// TotalSegmentsNotIn applies the NotIn predicate on the "total_segments" field.
func TotalSegmentsNotIn(vs ...int) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldNotIn(FieldTotalSegments, vs...))
}

// TotalSegmentsGT applies the GT predicate on the "total_segments" field.
func TotalSegmentsGT(v int) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldGT(FieldTotalSegments, v))
}

// TotalSegmentsGTE applies the GTE predicate on the "total_segments" field.
func TotalSegmentsGTE(v int) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldGTE(FieldTotalSegments, v))
}

// TotalSegmentsLT applies the LT predicate on the "total_segments" field.
func TotalSegmentsLT(v int) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldLT(FieldTotalSegments, v))
}

// TotalSegmentsLTE applies the LTE predicate on the "total_segments" field.
func TotalSegmentsLTE(v int) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldLTE(FieldTotalSegments, v))
}

// ProcessedSegmentsEQ applies the EQ predicate on the "processed_segments" field.
func ProcessedSegmentsEQ(v int) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldEQ(FieldProcessedSegments, v))
}

// ProcessedSegmentsNEQ applies the NEQ predicate on the "processed_segments" field.
func ProcessedSegmentsNEQ(v int) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldNEQ(FieldProcessedSegments, v))
}

// ProcessedSegmentsIn applies the In predicate on the "processed_segments" field.
func ProcessedSegmentsIn(vs ...int) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldIn(FieldProcessedSegments, vs...))
}

// ProcessedSegmentsNotIn applies the NotIn predicate on the "processed_segments" field.
func ProcessedSegmentsNotIn(vs ...int) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldNotIn(FieldProcessedSegments, vs...))
}

// ProcessedSegmentsGT applies the GT predicate on the "processed_segments" field.
func ProcessedSegmentsGT(v int) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldGT(FieldProcessedSegments, v))
}

// ProcessedSegmentsGTE applies the GTE predicate on the "processed_segments" field.
func ProcessedSegmentsGTE(v int) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldGTE(FieldProcessedSegments, v))
}

// ProcessedSegmentsLT applies the LT predicate on the "processed_segments" field.
func ProcessedSegmentsLT(v int) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldLT(FieldProcessedSegments, v))
}

// ProcessedSegmentsLTE applies the LTE predicate on the "processed_segments" field.
func ProcessedSegmentsLTE(v int) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldLTE(FieldProcessedSegments, v))
}

// SuccessfulSegmentsEQ applies the EQ predicate on the "successful_segments" field.
func SuccessfulSegmentsEQ(v int) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldEQ(FieldSuccessfulSegments, v))
}

// SuccessfulSegmentsNEQ applies the NEQ predicate on the "successful_segments" field.
func SuccessfulSegmentsNEQ(v int) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldNEQ(FieldSuccessfulSegments, v))
}

// SuccessfulSegmentsIn applies the In predicate on the "successful_segments" field.
func SuccessfulSegmentsIn(vs ...int) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldIn(FieldSuccessfulSegments, vs...))
}

// SuccessfulSegmentsNotIn applies the NotIn predicate on the "successful_segments" field.
func SuccessfulSegmentsNotIn(vs ...int) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldNotIn(FieldSuccessfulSegments, vs...))
}

// SuccessfulSegmentsGT applies the GT predicate on the "successful_segments" field.
func SuccessfulSegmentsGT(v int) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldGT(FieldSuccessfulSegments, v))
}

// SuccessfulSegmentsGTE applies the GTE predicate on the "successful_segments" field.
func SuccessfulSegmentsGTE(v int) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldGTE(FieldSuccessfulSegments, v))
}

// SuccessfulSegmentsLT applies the LT predicate on the "successful_segments" field.
func SuccessfulSegmentsLT(v int) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldLT(FieldSuccessfulSegments, v))
}

// SuccessfulSegmentsLTE applies the LTE predicate on the "successful_segments" field.
func SuccessfulSegmentsLTE(v int) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldLTE(FieldSuccessfulSegments, v))
}

// FailedSegmentsEQ applies the EQ predicate on the "failed_segments" field.
func FailedSegmentsEQ(v int) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldEQ(FieldFailedSegments, v))
}

// FailedSegmentsNEQ applies the NEQ predicate on the "failed_segments" field.
func FailedSegmentsNEQ(v int) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldNEQ(FieldFailedSegments, v))
}

// FailedSegmentsIn applies the In predicate on the "failed_segments" field.
func FailedSegmentsIn(vs ...int) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldIn(FieldFailedSegments, vs...))
}

// FailedSegmentsNotIn applies the NotIn predicate on the "failed_segments" field.
func FailedSegmentsNotIn(vs ...int) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldNotIn(FieldFailedSegments, vs...))
}

// FailedSegmentsGT applies the GT predicate on the "failed_segments" field.
func FailedSegmentsGT(v int) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldGT(FieldFailedSegments, v))
}

// FailedSegmentsGTE applies the GTE predicate on the "failed_segments" field.
func FailedSegmentsGTE(v int) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldGTE(FieldFailedSegments, v))
}

// FailedSegmentsLT applies the LT predicate on the "failed_segments" field.
func FailedSegmentsLT(v int) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldLT(FieldFailedSegments, v))
}

// FailedSegmentsLTE applies the LTE predicate on the "failed_segments" field.
func FailedSegmentsLTE(v int) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldLTE(FieldFailedSegments, v))
}

// LaneEQ applies the EQ predicate on the "lane" field.
func LaneEQ(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldEQ(FieldLane, v))
}

// LaneNEQ applies the NEQ predicate on the "lane" field.
func LaneNEQ(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldNEQ(FieldLane, v))
}

// LaneIn applies the In predicate on the "lane" field.
func LaneIn(vs ...string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldIn(FieldLane, vs...))
}

// LaneNotIn applies the NotIn predicate on the "lane" field.
func LaneNotIn(vs ...string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldNotIn(FieldLane, vs...))
}

// LaneGT applies the GT predicate on the "lane" field.
func LaneGT(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldGT(FieldLane, v))
}

// LaneGTE applies the GTE predicate on the "lane" field.
func LaneGTE(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldGTE(FieldLane, v))
}

// LaneLT applies the LT predicate on the "lane" field.
func LaneLT(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldLT(FieldLane, v))
}

// LaneLTE applies the LTE predicate on the "lane" field.
func LaneLTE(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldLTE(FieldLane, v))
}

// LaneContains applies the Contains predicate on the "lane" field.
func LaneContains(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldContains(FieldLane, v))
}

// LaneHasPrefix applies the HasPrefix predicate on the "lane" field.
func LaneHasPrefix(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldHasPrefix(FieldLane, v))
}

// LaneHasSuffix applies the HasSuffix predicate on the "lane" field.
func LaneHasSuffix(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldHasSuffix(FieldLane, v))
}

// LaneEqualFold applies the EqualFold predicate on the "lane" field.
func LaneEqualFold(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldEqualFold(FieldLane, v))
}

// LaneContainsFold applies the ContainsFold predicate on the "lane" field.
func LaneContainsFold(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldContainsFold(FieldLane, v))
}

// ReasonCodeEQ applies the EQ predicate on the "reason_code" field.
func ReasonCodeEQ(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldEQ(FieldReasonCode, v))
}

// ReasonCodeNEQ applies the NEQ predicate on the "reason_code" field.
func ReasonCodeNEQ(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldNEQ(FieldReasonCode, v))
}

// ReasonCodeIn applies the In predicate on the "reason_code" field.
func ReasonCodeIn(vs ...string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldIn(FieldReasonCode, vs...))
}

// ReasonCodeNotIn applies the NotIn predicate on the "reason_code" field.
func ReasonCodeNotIn(vs ...string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldNotIn(FieldReasonCode, vs...))
}

// ReasonCodeGT applies the GT predicate on the "reason_code" field.
func ReasonCodeGT(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldGT(FieldReasonCode, v))
}

// ReasonCodeGTE applies the GTE predicate on the "reason_code" field.
func ReasonCodeGTE(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldGTE(FieldReasonCode, v))
}

// ReasonCodeLT applies the LT predicate on the "reason_code" field.
func ReasonCodeLT(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldLT(FieldReasonCode, v))
}

// ReasonCodeLTE applies the LTE predicate on the "reason_code" field.
func ReasonCodeLTE(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldLTE(FieldReasonCode, v))
}

// ReasonCodeContains applies the Contains predicate on the "reason_code" field.
func ReasonCodeContains(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldContains(FieldReasonCode, v))
}

// ReasonCodeHasPrefix applies the HasPrefix predicate on the "reason_code" field.
func ReasonCodeHasPrefix(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldHasPrefix(FieldReasonCode, v))
}

// ReasonCodeHasSuffix applies the HasSuffix predicate on the "reason_code" field.
func ReasonCodeHasSuffix(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldHasSuffix(FieldReasonCode, v))
}

// ReasonCodeIsNil applies the IsNil predicate on the "reason_code" field.
func ReasonCodeIsNil() predicate.SyncJob {
	return predicate.SyncJob(sql.FieldIsNull(FieldReasonCode))
}

// ReasonCodeNotNil applies the NotNil predicate on the "reason_code" field.
func ReasonCodeNotNil() predicate.SyncJob {
	return predicate.SyncJob(sql.FieldNotNull(FieldReasonCode))
}

// ReasonCodeEqualFold applies the EqualFold predicate on the "reason_code" field.
func ReasonCodeEqualFold(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldEqualFold(FieldReasonCode, v))
}

// ReasonCodeContainsFold applies the ContainsFold predicate on the "reason_code" field.
func ReasonCodeContainsFold(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldContainsFold(FieldReasonCode, v))
}

// RetryAfterEQ applies the EQ predicate on the "retry_after" field.
func RetryAfterEQ(v int) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldEQ(FieldRetryAfter, v))
}

// RetryAfterNEQ applies the NEQ predicate on the "retry_after" field.
func RetryAfterNEQ(v int) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldNEQ(FieldRetryAfter, v))
}

// RetryAfterIn applies the In predicate on the "retry_after" field.
func RetryAfterIn(vs ...int) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldIn(FieldRetryAfter, vs...))
}

// RetryAfterNotIn applies the NotIn predicate on the "retry_after" field.
func RetryAfterNotIn(vs ...int) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldNotIn(FieldRetryAfter, vs...))
}

// RetryAfterGT applies the GT predicate on the "retry_after" field.
func RetryAfterGT(v int) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldGT(FieldRetryAfter, v))
}

// RetryAfterGTE applies the GTE predicate on the "retry_after" field.
func RetryAfterGTE(v int) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldGTE(FieldRetryAfter, v))
}

// RetryAfterLT applies the LT predicate on the "retry_after" field.
func RetryAfterLT(v int) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldLT(FieldRetryAfter, v))
}

// RetryAfterLTE applies the LTE predicate on the "retry_after" field.
func RetryAfterLTE(v int) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldLTE(FieldRetryAfter, v))
}

// RetryAfterIsNil applies the IsNil predicate on the "retry_after" field.
func RetryAfterIsNil() predicate.SyncJob {
	return predicate.SyncJob(sql.FieldIsNull(FieldRetryAfter))
}

// RetryAfterNotNil applies the NotNil predicate on the "retry_after" field.
func RetryAfterNotNil() predicate.SyncJob {
	return predicate.SyncJob(sql.FieldNotNull(FieldRetryAfter))
}

// RecordingAgeSecondsEQ applies the EQ predicate on the "recording_age_seconds" field.
func RecordingAgeSecondsEQ(v int) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldEQ(FieldRecordingAgeSeconds, v))
}

// RecordingAgeSecondsNEQ applies the NEQ predicate on the "recording_age_seconds" field.
func RecordingAgeSecondsNEQ(v int) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldNEQ(FieldRecordingAgeSeconds, v))
}

// RecordingAgeSecondsIn applies the In predicate on the "recording_age_seconds" field.
func RecordingAgeSecondsIn(vs ...int) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldIn(FieldRecordingAgeSeconds, vs...))
}

// RecordingAgeSecondsNotIn applies the NotIn predicate on the "recording_age_seconds" field.
func RecordingAgeSecondsNotIn(vs ...int) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldNotIn(FieldRecordingAgeSeconds, vs...))
}

// RecordingAgeSecondsGT applies the GT predicate on the "recording_age_seconds" field.
func RecordingAgeSecondsGT(v int) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldGT(FieldRecordingAgeSeconds, v))
}

// RecordingAgeSecondsGTE applies the GTE predicate on the "recording_age_seconds" field.
func RecordingAgeSecondsGTE(v int) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldGTE(FieldRecordingAgeSeconds, v))
}

// RecordingAgeSecondsLT applies the LT predicate on the "recording_age_seconds" field.
func RecordingAgeSecondsLT(v int) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldLT(FieldRecordingAgeSeconds, v))
}

// RecordingAgeSecondsLTE applies the LTE predicate on the "recording_age_seconds" field.
func RecordingAgeSecondsLTE(v int) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldLTE(FieldRecordingAgeSeconds, v))
}

// RecordingAgeSecondsIsNil applies the IsNil predicate on the "recording_age_seconds" field.
func RecordingAgeSecondsIsNil() predicate.SyncJob {
	return predicate.SyncJob(sql.FieldIsNull(FieldRecordingAgeSeconds))
}

// RecordingAgeSecondsNotNil applies the NotNil predicate on the "recording_age_seconds" field.
func RecordingAgeSecondsNotNil() predicate.SyncJob {
	return predicate.SyncJob(sql.FieldNotNull(FieldRecordingAgeSeconds))
}

// ErrorEQ applies the EQ predicate on the "error" field.
func ErrorEQ(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldEQ(FieldError, v))
}

// ErrorNEQ applies the NEQ predicate on the "error" field.
func ErrorNEQ(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldNEQ(FieldError, v))
}

// ErrorIn applies the In predicate on the "error" field.
func ErrorIn(vs ...string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldIn(FieldError, vs...))
}

// ErrorNotIn applies the NotIn predicate on the "error" field.
func ErrorNotIn(vs ...string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldNotIn(FieldError, vs...))
}

// ErrorGT applies the GT predicate on the "error" field.
func ErrorGT(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldGT(FieldError, v))
}

// ErrorGTE applies the GTE predicate on the "error" field.
func ErrorGTE(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldGTE(FieldError, v))
}

// ErrorLT applies the LT predicate on the "error" field.
func ErrorLT(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldLT(FieldError, v))
}

// ErrorLTE applies the LTE predicate on the "error" field.
func ErrorLTE(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldLTE(FieldError, v))
}

// ErrorContains applies the Contains predicate on the "error" field.
func ErrorContains(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldContains(FieldError, v))
}

// ErrorHasPrefix applies the HasPrefix predicate on the "error" field.
func ErrorHasPrefix(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldHasPrefix(FieldError, v))
}

// ErrorHasSuffix applies the HasSuffix predicate on the "error" field.
func ErrorHasSuffix(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldHasSuffix(FieldError, v))
}

// ErrorIsNil applies the IsNil predicate on the "error" field.
func ErrorIsNil() predicate.SyncJob {
	return predicate.SyncJob(sql.FieldIsNull(FieldError))
}

// ErrorNotNil applies the NotNil predicate on the "error" field.
func ErrorNotNil() predicate.SyncJob {
	return predicate.SyncJob(sql.FieldNotNull(FieldError))
}

// ErrorEqualFold applies the EqualFold predicate on the "error" field.
func ErrorEqualFold(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldEqualFold(FieldError, v))
}

// ErrorContainsFold applies the ContainsFold predicate on the "error" field.
func ErrorContainsFold(v string) predicate.SyncJob {
	return predicate.SyncJob(sql.FieldContainsFold(FieldError, v))
}

// ResultIsNil applies the IsNil predicate on the "result" field.
func ResultIsNil() predicate.SyncJob {
	return predicate.SyncJob(sql.FieldIsNull(FieldResult))
}

// ResultNotNil applies the NotNil predicate on the "result" field.
func ResultNotNil() predicate.SyncJob {
	return predicate.SyncJob(sql.FieldNotNull(FieldResult))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SyncJob) predicate.SyncJob {
	return predicate.SyncJob(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SyncJob) predicate.SyncJob {
	return predicate.SyncJob(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SyncJob) predicate.SyncJob {
	return predicate.SyncJob(sql.NotPredicates(p))
}
