// Code generated by ent, DO NOT EDIT.

package calendarmeeting

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the calendarmeeting type in the database.
	Label = "calendar_meeting"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldExternalID holds the string denoting the external_id field in the database.
	FieldExternalID = "external_id"
	// FieldCalendarEventID holds the string denoting the calendar_event_id field in the database.
	FieldCalendarEventID = "calendar_event_id"
	// FieldCalendarSource holds the string denoting the calendar_source field in the database.
	FieldCalendarSource = "calendar_source"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldParticipants holds the string denoting the participants field in the database.
	FieldParticipants = "participants"
	// FieldPlatform holds the string denoting the platform field in the database.
	FieldPlatform = "platform"
	// FieldMeetingLink holds the string denoting the meeting_link field in the database.
	FieldMeetingLink = "meeting_link"
	// FieldStartTime holds the string denoting the start_time field in the database.
	FieldStartTime = "start_time"
	// FieldEndTime holds the string denoting the end_time field in the database.
	FieldEndTime = "end_time"
	// FieldDurationMinutes holds the string denoting the duration_minutes field in the database.
	FieldDurationMinutes = "duration_minutes"
	// FieldNotes holds the string denoting the notes field in the database.
	FieldNotes = "notes"
	// FieldSyncedAt holds the string denoting the synced_at field in the database.
	FieldSyncedAt = "synced_at"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the calendarmeeting in the database.
	Table = "calendar_meetings"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "calendar_meetings"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
)

// Columns holds all SQL columns for calendarmeeting fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldExternalID,
	FieldCalendarEventID,
	FieldCalendarSource,
	FieldTitle,
	FieldParticipants,
	FieldPlatform,
	FieldMeetingLink,
	FieldStartTime,
	FieldEndTime,
	FieldDurationMinutes,
	FieldNotes,
	FieldSyncedAt,
	FieldUserID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// CalendarEventIDValidator is a validator for the "calendar_event_id" field. It is called by the builders before save.
	CalendarEventIDValidator func(string) error
	// DefaultCalendarSource holds the default value on creation for the "calendar_source" field.
	DefaultCalendarSource string
	// TitleValidator is a validator for the "title" field. It is called by the builders before save.
	TitleValidator func(string) error
)

// OrderOption defines the ordering options for the CalendarMeeting queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByExternalID orders the results by the external_id field.
func ByExternalID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExternalID, opts...).ToFunc()
}

// ByCalendarEventID orders the results by the calendar_event_id field.
func ByCalendarEventID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCalendarEventID, opts...).ToFunc()
}

// ByCalendarSource orders the results by the calendar_source field.
func ByCalendarSource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCalendarSource, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByPlatform orders the results by the platform field.
func ByPlatform(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlatform, opts...).ToFunc()
}

// ByMeetingLink orders the results by the meeting_link field.
func ByMeetingLink(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMeetingLink, opts...).ToFunc()
}

// ByStartTime orders the results by the start_time field.
func ByStartTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartTime, opts...).ToFunc()
}

// ByEndTime orders the results by the end_time field.
func ByEndTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEndTime, opts...).ToFunc()
}

// ByDurationMinutes orders the results by the duration_minutes field.
func ByDurationMinutes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDurationMinutes, opts...).ToFunc()
}

// ByNotes orders the results by the notes field.
func ByNotes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotes, opts...).ToFunc()
}

// BySyncedAt orders the results by the synced_at field.
func BySyncedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSyncedAt, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
